"""Shared pixel-art helpers for Hearthstead's deterministic texture pipeline.

Every texture in the mod is generated by code in this folder so the art is
original by construction, exactly sized, and reproducible. Light convention:
top-left key light — top faces brightest, front neutral, sides dimmed, back
and bottom darkest.
"""
import colorsys
import math
import random
from collections.abc import Mapping, Set as AbstractSet
from numbers import Real
from PIL import Image

# ---------------------------------------------------------------- palette ---
# Grounded European medieval palette.  Each ramp is dark -> light and is
# generated from a compact design token rather than hand-tuned RGB literals.
# This keeps every downstream generator on one enforceable colour doctrine.
#
# ``hue`` and ``hue_drift`` are degrees at the dark stop and total movement
# toward the highlight.  Warm ramps drift +10..15 degrees; cool ramps drift
# -12..18 degrees.  Skin is the deliberate exception: its narrow warm band
# never travels into blue/gray shadows.
_CHROMA_CURVE = (0.78, 1.00, 0.93, 0.72, 0.55)
_SKIN_CHROMA_CURVE = (0.82, 1.00, 0.94, 0.78, 0.64)


def _finite_real(name, candidate):
    """Return a finite ``float`` for a numeric token or raise ``ValueError``.

    ``bool`` is deliberately excluded even though Python considers it an
    ``int``.  Converting before the finite check also turns exotic/oversized
    ``Real`` implementations into the same public ``ValueError`` contract
    instead of leaking ``TypeError`` or ``OverflowError``.
    """
    if not isinstance(candidate, Real) or isinstance(candidate, bool):
        raise ValueError(f"{name} must be a finite real number (not bool)")
    try:
        result = float(candidate)
    except Exception:
        raise ValueError(f"{name} must be a finite real number (not bool)") from None
    if not math.isfinite(result):
        raise ValueError(f"{name} must be a finite real number (not bool)")
    return result


def _finite_real_sequence(name, candidate, expected_length):
    """Normalise a fixed-length numeric sequence to a tuple of finite floats."""
    if isinstance(candidate, (str, bytes, bytearray, Mapping, AbstractSet)):
        raise ValueError(
            f"{name} must contain exactly {expected_length} finite real numbers")
    try:
        values = tuple(candidate)
    except Exception:
        raise ValueError(
            f"{name} must contain exactly {expected_length} finite real numbers") from None
    if len(values) != expected_length:
        raise ValueError(
            f"{name} must contain exactly {expected_length} finite real numbers")
    return tuple(_finite_real(f"{name}[{index}]", value)
                 for index, value in enumerate(values))


def make_ramp(*, hue, saturation, value, hue_drift, value_steps,
              family="warm", chroma_curve=None):
    """Build one deterministic five-stop HSV ramp as ``#rrggbb`` strings.

    ``value``/``saturation`` are HSV percentages.  The constructor validates
    B1's hard numeric contract up front so an invalid token cannot silently
    reach a texture generator.
    """
    if not isinstance(family, str) or family not in ("warm", "cool", "skin"):
        raise ValueError("family must be one of: warm, cool, skin")

    hue = _finite_real("hue", hue)
    saturation = _finite_real("saturation", saturation)
    value = _finite_real("value", value)
    hue_drift = _finite_real("hue_drift", hue_drift)
    value_steps = _finite_real_sequence("value_steps", value_steps, 4)

    if not 0.0 <= hue < 360.0:
        raise ValueError("hue must stay inside [0, 360)")
    if any(not 8 <= step <= 11 for step in value_steps):
        raise ValueError("value_steps must contain four values in the 8..11 range")
    if sum(value_steps) < 32:
        raise ValueError("a ramp must span at least 32 HSV-V points")
    if value < 12 or value + sum(value_steps) > 96:
        raise ValueError("ramp endpoints must stay inside HSV-V 12..96")
    if not 0 < saturation <= 90:
        raise ValueError("peak saturation must stay inside 1..90")
    if family == "warm" and not 10 <= hue_drift <= 15:
        raise ValueError("warm ramps require +10..15 degrees of hue drift")
    if family == "cool" and not -18 <= hue_drift <= -12:
        raise ValueError("cool ramps require -12..18 degrees of hue drift")
    if family == "skin" and abs(hue_drift) > 10:
        raise ValueError("skin hue drift must remain within 10 degrees")

    curve_source = (_SKIN_CHROMA_CURVE if family == "skin" else _CHROMA_CURVE) \
        if chroma_curve is None else chroma_curve
    curve = _finite_real_sequence("chroma_curve", curve_source, 5)
    if any(not 0.0 < point <= 1.0 for point in curve):
        raise ValueError("chroma_curve values must stay inside (0, 1]")
    peak = max(curve)
    if not math.isclose(peak, 1.0, rel_tol=0.0, abs_tol=1.0e-9):
        raise ValueError("chroma_curve peak must be exactly 1.0")
    if not any(math.isclose(curve[index], peak, rel_tol=0.0, abs_tol=1.0e-9)
               for index in (1, 2)):
        raise ValueError("chroma must peak at stop 1 or 2")
    if any(math.isclose(curve[index], peak, rel_tol=0.0, abs_tol=1.0e-9)
           for index in (0, 3, 4)):
        raise ValueError("chroma peak cannot extend outside stops 1 and 2")
    shadow_ratio = curve[0] / peak
    highlight_ratio = curve[4] / peak
    if not 0.68 <= shadow_ratio <= 0.92:
        raise ValueError("shadow chroma must be 0.68..0.92 of the peak")
    if not 0.38 <= highlight_ratio <= 0.72:
        raise ValueError("highlight chroma must be 0.38..0.72 of the peak")

    values = [value]
    for step in value_steps:
        values.append(values[-1] + step)

    result = []
    for index in range(5):
        stop_hue = (hue + hue_drift * index / 4.0) % 360.0
        stop_sat = saturation * curve[index]
        red, green, blue = colorsys.hsv_to_rgb(
            stop_hue / 360.0, stop_sat / 100.0, values[index] / 100.0)
        rgb = tuple(max(0, min(255, int(channel * 255 + 0.5)))
                    for channel in (red, green, blue))
        result.append("#{:02x}{:02x}{:02x}".format(*rgb))
    return result


# B1 palette tokens.  ``family`` is both design intent and validator input;
# do not remove it in favour of inferring temperature from a palette name.
PALETTE_TOKENS = {
    "linen":       dict(hue=34,  saturation=30, value=56, hue_drift=12, family="warm", value_steps=(10, 10, 10, 10)),
    "linen_raw":   dict(hue=32,  saturation=34, value=50, hue_drift=12, family="warm", value_steps=(10, 10, 9, 9)),
    "oak":         dict(hue=25,  saturation=66, value=20, hue_drift=14, family="warm", value_steps=(8, 9, 9, 10)),
    "oak_light":   dict(hue=27,  saturation=58, value=28, hue_drift=13, family="warm", value_steps=(9, 9, 9, 9)),
    "stone":       dict(hue=226, saturation=18, value=28, hue_drift=-16, family="cool", value_steps=(9, 9, 9, 9)),
    "leather":     dict(hue=24,  saturation=75, value=23, hue_drift=14, family="warm", value_steps=(10, 9, 9, 9)),
    "burgundy":    dict(hue=340, saturation=62, value=24, hue_drift=13, family="warm", value_steps=(9, 9, 9, 9)),
    "forest":      dict(hue=118, saturation=45, value=24, hue_drift=-14, family="cool", value_steps=(9, 9, 9, 9)),
    "wheat":       dict(hue=34,  saturation=78, value=42, hue_drift=13, family="warm", value_steps=(10, 10, 9, 9)),
    "iron":        dict(hue=230, saturation=24, value=17, hue_drift=-16, family="cool", value_steps=(9, 9, 9, 9)),
    "amber":       dict(hue=27,  saturation=84, value=55, hue_drift=14, family="warm", value_steps=(10, 10, 10, 10)),
    "ember":       dict(hue=8,   saturation=88, value=48, hue_drift=15, family="warm", value_steps=(11, 10, 10, 10)),
    "skin":        dict(hue=20,  saturation=62, value=50, hue_drift=8, family="skin", value_steps=(9, 9, 9, 9)),
    "skin_tan":    dict(hue=19,  saturation=70, value=40, hue_drift=8, family="skin", value_steps=(9, 9, 9, 9)),
    "skin_deep":   dict(hue=18,  saturation=72, value=22, hue_drift=8, family="skin", value_steps=(10, 10, 10, 10)),
    "skin_pale":   dict(hue=20,  saturation=50, value=57, hue_drift=8, family="skin", value_steps=(9, 9, 9, 9)),
    "hair_brn":    dict(hue=20,  saturation=80, value=15, hue_drift=14, family="warm", value_steps=(8, 8, 8, 8)),
    "hair_blnd":   dict(hue=31,  saturation=72, value=32, hue_drift=13, family="warm", value_steps=(9, 10, 10, 10)),
    "hair_blk":    dict(hue=260, saturation=22, value=13, hue_drift=-14, family="cool", value_steps=(8, 8, 8, 8)),
    "hair_red":    dict(hue=10,  saturation=85, value=24, hue_drift=14, family="warm", value_steps=(10, 10, 10, 10)),
    "wool_gray":   dict(hue=228, saturation=15, value=27, hue_drift=-15, family="cool", value_steps=(9, 9, 9, 9)),
    "gambeson":    dict(hue=37,  saturation=26, value=34, hue_drift=12, family="warm", value_steps=(9, 9, 9, 9)),
    "straw":       dict(hue=36,  saturation=76, value=39, hue_drift=13, family="warm", value_steps=(10, 10, 9, 9)),
    "parchment":   dict(hue=35,  saturation=40, value=55, hue_drift=11, family="warm", value_steps=(10, 9, 9, 9)),
    "ink":         dict(hue=25,  saturation=58, value=16, hue_drift=12, family="warm", value_steps=(9, 9, 9, 9)),
    "oak_carved":  dict(hue=24,  saturation=70, value=14, hue_drift=14, family="warm", value_steps=(8, 9, 9, 10)),
    "iron_forged": dict(hue=234, saturation=25, value=13, hue_drift=-14, family="cool", value_steps=(9, 9, 9, 9)),
    "brass":       dict(hue=36,  saturation=80, value=38, hue_drift=12, family="warm", value_steps=(10, 10, 10, 10)),
    "charcoal":    dict(hue=272, saturation=16, value=12, hue_drift=-18, family="cool", value_steps=(8, 8, 9, 9)),
    "bone":        dict(hue=38,  saturation=20, value=42, hue_drift=11, family="warm", value_steps=(10, 10, 10, 10)),
    "emerald":     dict(hue=145, saturation=65, value=26, hue_drift=-14, family="cool", value_steps=(10, 10, 10, 10)),
    "crimson":     dict(hue=345, saturation=78, value=26, hue_drift=13, family="warm", value_steps=(10, 10, 10, 9)),
}

PALETTES = {name: make_ramp(**token) for name, token in PALETTE_TOKENS.items()}


def hx(s):
    """'#rrggbb' -> (r, g, b, 255)."""
    s = s.lstrip("#")
    return (int(s[0:2], 16), int(s[2:4], 16), int(s[4:6], 16), 255)


def ramp(name):
    return [hx(c) for c in PALETTES[name]]


def shade(color, f):
    r, g, b, a = color
    return (max(0, min(255, int(r * f))), max(0, min(255, int(g * f))),
            max(0, min(255, int(b * f))), a)


def mix(c1, c2, t):
    return tuple(int(a + (b - a) * t) for a, b in zip(c1, c2))


def new_image(w, h):
    return Image.new("RGBA", (w, h), (0, 0, 0, 0))


def fill(img, x, y, w, h, color):
    px = img.load()
    for j in range(y, y + h):
        for i in range(x, x + w):
            if 0 <= i < img.width and 0 <= j < img.height:
                px[i, j] = color


def put(img, x, y, color):
    if 0 <= x < img.width and 0 <= y < img.height:
        img.load()[x, y] = color


def cloth(img, x, y, w, h, ramp_colors, rng, base_idx=3, weave=0.35,
          v_grad=0.12, h_grad=0.0):
    """Fabric fill: base tone + woven noise + a soft vertical gradient."""
    px = img.load()
    n = len(ramp_colors)
    for j in range(h):
        gv = 1.0 - v_grad * (j / max(1, h - 1))
        for i in range(w):
            gh = 1.0 - h_grad * abs((i / max(1, w - 1)) - 0.5) * 2
            idx = base_idx
            r = rng.random()
            if r < weave * 0.45:
                idx = max(0, base_idx - 1)
            elif r < weave * 0.55:
                idx = min(n - 1, base_idx + 1)
            elif r < weave * 0.60:
                idx = max(0, base_idx - 2)
            c = shade(ramp_colors[idx], gv * gh)
            px[x + i, y + j] = c


_MATERIAL_PERIOD = 16


def _period_partition(period, bounds, rng):
    """Randomly partition ``period`` while keeping every part in bounds."""
    low, high = bounds
    if low < 2 or high < low or low > period:
        raise ValueError(f"invalid periodic partition bounds: {bounds}")
    remaining = period
    parts = []
    while remaining:
        choices = []
        for candidate in range(low, high + 1):
            tail = remaining - candidate
            if tail == 0 or (tail >= low and (tail + high - 1) // high <= tail // low):
                choices.append(candidate)
        if not choices:
            raise ValueError(f"cannot partition {period} with bounds {bounds}")
        choice = rng.choice(choices)
        parts.append(choice)
        remaining -= choice
    return parts


def _ring_segments(widths, offset):
    """Map a 16-wide ring to (segment index, local x, segment width)."""
    starts = []
    cursor = 0
    for width in widths:
        starts.append(cursor)
        cursor += width
    result = []
    for x in range(_MATERIAL_PERIOD):
        ring_x = (x - offset) % _MATERIAL_PERIOD
        for index, start in enumerate(starts):
            width = widths[index]
            if start <= ring_x < start + width:
                result.append((index, ring_x - start, width))
                break
    return result


def _edgeable_stone_partition(parts, bounds):
    """Ensure a course/stone contains at least two material texels.

    A two-texel part consists of one stone texel and one mortar texel, so no
    tile cut can place real material on both sides of the wrap.  A 2..3/2..4
    profile can rarely partition sixteen as eight twos; rebalance that
    degenerate partition without changing its total or leaving the requested
    bounds.  Other profiles already contain a part of size three or more.
    """
    if any(part >= 3 for part in parts):
        return parts
    low, high = bounds
    if low == 2 and high >= 4 and len(parts) >= 2:
        return [4, *parts[2:]]
    if low == 2 and high >= 3 and len(parts) >= 3:
        return [3, 3, *parts[3:]]
    return parts


def _stone_edge_offsets(widths):
    """Return tile cuts whose two edge texels are real stone, not mortar."""
    offsets = []
    for candidate in range(_MATERIAL_PERIOD):
        segments = _ring_segments(widths, candidate)
        left = segments[_MATERIAL_PERIOD - 1]
        right = segments[0]
        same_stone = left[0] == right[0]
        left_is_stone = left[1] < left[2] - 1
        right_is_stone = right[1] < right[2] - 1
        if same_stone and left_is_stone and right_is_stone:
            offsets.append(candidate)
    return offsets


def stone(img, x, y, w, h, ramp_colors, rng, block_w=(3, 5), block_h=(2, 3)):
    """Paint 16-periodic fieldstone with staggered, irregular courses.

    The former implementation clipped a random course at every texture edge,
    so its right/bottom fragments did not continue at the next tile.  This
    builds one complete toroidal 16x16 material cell first, then wraps it into
    any target rectangle.  Rendering 48x48 is therefore byte-identical to a
    3x3 paste of the corresponding 16x16 tile.
    """
    if len(ramp_colors) < 5:
        raise ValueError("stone requires a five-stop ramp")

    period = _MATERIAL_PERIOD
    mortar = shade(ramp_colors[0], 0.85)
    pattern = Image.new("RGBA", (period, period), mortar)
    pixels = pattern.load()
    course_heights = _edgeable_stone_partition(
        _period_partition(period, block_h, rng), block_h)
    row_course = [-1] * period
    row_is_stone = [False] * period
    course_y = 0
    previous_offset = None

    for course_index, course_height in enumerate(course_heights):
        widths = _edgeable_stone_partition(
            _period_partition(period, block_w, rng), block_w)
        # Pick a random course offset whose edge texels are inside the same
        # stone.  This removes the vertical gridline at the 15->0 wrap while
        # retaining independently staggered joints inside each course.
        safe_offsets = _stone_edge_offsets(widths)
        if not safe_offsets:
            raise ValueError(
                f"stone block_w={block_w} cannot place real stone on both tile edges")
        if previous_offset in safe_offsets and len(safe_offsets) > 1:
            safe_offsets.remove(previous_offset)
        offset = rng.choice(safe_offsets)
        previous_offset = offset
        segments = _ring_segments(widths, offset)
        stone_bases = [rng.choice(ramp_colors[1:4]) for _ in widths]
        stone_variance = [0.94 + rng.random() * 0.12 for _ in widths]

        for local_y in range(course_height):
            py = course_y + local_y
            row_course[py] = course_index
            if local_y == course_height - 1:
                continue  # one logical mortar row per course
            row_is_stone[py] = True
            for px, (segment_index, local_x, segment_width) in enumerate(segments):
                if local_x == segment_width - 1:
                    continue  # vertical mortar joint
                factor = stone_variance[segment_index]
                if local_y == 0:
                    factor = min(1.12, factor * 1.08)  # top-left key catch
                elif local_y == course_height - 2:
                    factor = max(0.88, factor * 0.92)  # lower weather shadow
                if local_x == 0:
                    factor = min(1.12, factor * 1.03)
                pixels[px, py] = shade(stone_bases[segment_index], factor)
        course_y += course_height

    # Rotate the torus so its vertical texture edge also cuts through the
    # interior of one course instead of landing on a clipped mortar/highlight
    # pair.  This is the vertical counterpart to the safe horizontal offset.
    safe_boundaries = [
        py for py in range(period)
        if row_is_stone[py] and row_is_stone[(py + 1) % period]
        and row_course[py] == row_course[(py + 1) % period]
    ]
    if not safe_boundaries:
        raise ValueError(
            f"stone block_h={block_h} cannot place real stone on both tile edges")
    boundary = rng.choice(safe_boundaries)
    shift = (-(boundary + 1)) % period
    rotated = Image.new("RGBA", (period, period), mortar)
    rotated_pixels = rotated.load()
    for py in range(period):
        source_y = (py - shift) % period
        for px in range(period):
            rotated_pixels[px, py] = pixels[px, source_y]
    pattern = rotated

    target = img.load()
    source = pattern.load()
    for target_y in range(h):
        for target_x in range(w):
            px = x + target_x
            py = y + target_y
            if 0 <= px < img.width and 0 <= py < img.height:
                target[px, py] = source[target_x % period, target_y % period]


def metal(img, x, y, w, h, ramp_colors, rng, *, axis="vertical", forged=False):
    """Forged-metal primitive: dark-light-dark reflection and sparse peen."""
    if axis not in {"vertical", "horizontal"}:
        raise ValueError("metal axis must be 'vertical' or 'horizontal'")
    if len(ramp_colors) < 5:
        raise ValueError("metal requires a five-stop ramp")
    pixels = img.load()
    # Five of eight texels remain in stops 0-1; the stop-4 line is a crisp
    # reflection, not a gradient or dither band.
    reflection = (0, 0, 1, 3, 4, 1, 0, 0)
    for local_y in range(h):
        for local_x in range(w):
            across = local_x if axis == "vertical" else local_y
            pixels[x + local_x, y + local_y] = ramp_colors[reflection[across % 8]]

    if forged and w >= 4 and h >= 4:
        # Paired dark/lit pixels make each peen mark a dent under top-left key
        # light.  Marks stay off the boundary so a material tile never grows a
        # repeated border scar.
        marks = max(1, (w * h) // 72)
        for _ in range(marks):
            px = x + rng.randint(1, w - 2)
            py = y + rng.randint(1, h - 2)
            pixels[px, py] = ramp_colors[1]
            pixels[px - 1, py - 1] = ramp_colors[3]


def wood_grain(img, x, y, w, h, ramp_colors, rng, *, vertical=False, board=4):
    """Weathered boards with broken, axis-correct grain clusters."""
    if board < 3:
        raise ValueError("wood boards need at least three texels of width")
    pixels = img.load()
    for local_y in range(h):
        for local_x in range(w):
            across = local_x if vertical else local_y
            seam = (across % board) == board - 1
            if seam:
                color = ramp_colors[0]
            else:
                roll = rng.random()
                color = ramp_colors[2 if roll < 0.22 else 3]
                if across % board == 0:
                    color = shade(color, 1.08)  # lit edge below each seam
            pixels[x + local_x, y + local_y] = color

    across_length = w if vertical else h
    along_length = h if vertical else w
    for board_start in range(0, across_length, board):
        usable = min(board - 1, across_length - board_start)
        if usable <= 0:
            continue
        cursor = rng.randint(0, 3)
        while cursor < along_length:
            length = min(rng.randint(2, 5), along_length - cursor)
            cross = board_start + rng.randrange(usable)
            for delta in range(length):
                local_x, local_y = ((cross, cursor + delta) if vertical
                                    else (cursor + delta, cross))
                pixels[x + local_x, y + local_y] = ramp_colors[1]
            cursor += length + rng.randint(3, 7)


def planks(img, x, y, w, h, ramp_colors, rng, vertical=False, board=4):
    """Backward-compatible name for the B1 wood-grain primitive."""
    wood_grain(img, x, y, w, h, ramp_colors, rng,
               vertical=vertical, board=board)


def fold(img, x, y, length, ramp_colors, *, vertical=False):
    """Paint one cloth fold: a catch-light immediately before its crease."""
    for delta in range(length):
        if vertical:
            put(img, x - 1, y + delta, ramp_colors[4])
            put(img, x, y + delta, ramp_colors[1])
        else:
            put(img, x + delta, y - 1, ramp_colors[4])
            put(img, x + delta, y, ramp_colors[1])


def worn_edge(img, x, y, w, h, ramp_colors, rng, *,
              edges=("top", "left"), wear=0.35):
    """Add clustered leather/wood wear and sparse adjacent scuff nicks."""
    edge_set = set(edges)
    valid_edges = {"top", "bottom", "left", "right"}
    if not edge_set <= valid_edges:
        raise ValueError(f"unknown worn edge in {edges}")
    if not 0.0 <= wear <= 1.0:
        raise ValueError("wear must be in the 0..1 range")

    def edge_points(edge):
        if edge == "top":
            return [(x + i, y) for i in range(w)]
        if edge == "bottom":
            return [(x + i, y + h - 1) for i in range(w)]
        if edge == "left":
            return [(x, y + i) for i in range(h)]
        return [(x + w - 1, y + i) for i in range(h)]

    # Never consume RNG in caller/set iteration order.  Texture generation is
    # byte-reproducible across PYTHONHASHSEED values even when an unordered
    # collection is supplied by a future generator.
    for edge in ("top", "right", "bottom", "left"):
        if edge not in edge_set:
            continue
        points = edge_points(edge)
        cursor = rng.randint(0, 2)
        while cursor < len(points):
            if rng.random() < wear:
                length = rng.randint(2, 4)
                for point in points[cursor:cursor + length]:
                    put(img, *point, ramp_colors[4])
                cursor += length
            cursor += rng.randint(1, 3)

    # A maximum of two isolated low-value nicks; these are intentional scuffs,
    # not per-pixel noise.
    for _ in range(min(2, max(0, (w * h) // 96))):
        put(img, x + rng.randrange(w), y + rng.randrange(h), ramp_colors[1])


def outline_rect(img, x, y, w, h, color):
    for i in range(x, x + w):
        put(img, i, y, color)
        put(img, i, y + h - 1, color)
    for j in range(y, y + h):
        put(img, x, j, color)
        put(img, x + w - 1, j, color)


def bevel(img, x, y, w, h, light, dark):
    """1px raised bevel: light on top/left, dark on bottom/right."""
    for i in range(x, x + w):
        put(img, i, y, light)
        put(img, i, y + h - 1, dark)
    for j in range(y, y + h):
        put(img, x, j, light)
        put(img, x + w - 1, j, dark)
    put(img, x + w - 1, y, mix(light, dark, 0.5))
    put(img, x, y + h - 1, mix(light, dark, 0.5))


def inset(img, x, y, w, h, light, dark):
    """1px sunken bevel: dark on top/left, light on bottom/right."""
    bevel(img, x, y, w, h, dark, light)


# ------------------------------------------------------------- box UV map ---
FACE_LIGHT = {"top": 1.14, "bottom": 0.62, "front": 1.0,
              "back": 0.82, "right": 0.90, "left": 0.90}


def lit(color, face):
    return shade(color, FACE_LIGHT[face])


def woven(img, x, y, w, h, colors, rng, face, base_idx=3):
    """painter(face, x, y, w, h) paints unlit; lighting applied by painter."""
    px = img.load()
    n = len(colors)
    for j in range(h):
        for i in range(w):
            idx = base_idx
            r = rng.random()
            if r < 0.16:
                idx = max(0, base_idx - 1)
            elif r < 0.22:
                idx = min(n - 1, base_idx + 1)
            px[x + i, y + j] = lit(colors[idx], face)


def box_faces(u, v, w, h, d):
    """Vanilla box UV layout -> face name to (x, y, width, height) rects.

    Layout:  [top][bottom] on the first d rows,
             [right][front][left][back] below.
    """
    return {
        "top":    (u + d,         v,     w, d),
        "bottom": (u + d + w,     v,     w, d),
        "right":  (u,             v + d, d, h),
        "front":  (u + d,         v + d, w, h),
        "left":   (u + d + w,     v + d, d, h),
        "back":   (u + d + w + d, v + d, w, h),
    }


def paint_box(img, u, v, w, h, d, painter):
    """Call painter(face_name, x, y, fw, fh, light_factor) for all six faces."""
    for face, (x, y, fw, fh) in box_faces(u, v, w, h, d).items():
        painter(face, x, y, fw, fh, FACE_LIGHT[face])


def scale_check(img, expect_w, expect_h, name):
    assert img.size == (expect_w, expect_h), \
        f"{name}: {img.size} != {(expect_w, expect_h)}"


def save(img, path):
    import os
    os.makedirs(os.path.dirname(path), exist_ok=True)
    img.save(path)
    print(f"  wrote {path} ({img.width}x{img.height})")
