"""Hand-authored 16x16 job icons for Bannerhold (modid hearthstead).

Every pixel is written below as a character grid; nothing is generated or
filtered. Run:  python tools/ui/job_icons.py [--preview out.png]
Writes src/main/resources/assets/hearthstead/textures/gui/job/<key>.png, one
per Profession key. Style: dark warm outline, two or three tones per material,
light from the top left, 1px transparent margin (readable at 1x and 2x).
"""
import os
import sys

from PIL import Image

PALETTE = {
    '.': None,
    'k': (43, 29, 20),        # outline
    'w': (138, 90, 50), 'W': (185, 129, 80), 'd': (90, 56, 29),        # wood
    'i': (163, 168, 173), 'I': (223, 227, 230), 'j': (95, 100, 106),   # iron
    'g': (214, 162, 44), 'G': (243, 213, 124), 'h': (148, 104, 26),    # gold
    'r': (168, 50, 45), 'R': (217, 96, 79), 'e': (107, 31, 27),        # red
    'n': (79, 125, 58), 'N': (134, 173, 92), 'm': (46, 76, 34),        # green
    'b': (61, 108, 158), 'B': (126, 167, 210), 'c': (38, 68, 99),      # blue
    'o': (241, 234, 219), 'O': (214, 200, 170), 's': (141, 136, 128),  # wool / stone
    'S': (92, 88, 82),
    'l': (124, 74, 39), 'L': (173, 108, 59),                           # leather
    't': (198, 134, 57), 'T': (233, 180, 101), 'u': (143, 90, 34),     # bread / crust
    'x': (53, 49, 47), 'X': (93, 87, 82),                              # black iron
    'p': (107, 76, 163), 'P': (169, 141, 227), 'q': (67, 47, 107),     # rune glow
    'f': (232, 135, 42), 'F': (247, 209, 84),                          # flame
}

ICONS = {
    # Unassigned: a plain wooden peg tag with an empty ring -- "no trade yet".
    'none': [
        "................",
        "................",
        "......kkkk......",
        "....kkWWWWkk....",
        "...kWWWwwwwdk...",
        "...kWwwwwwwdk...",
        "..kWwwkkkkwwdk..",
        "..kWwkddddkwdk..",
        "..kWwkddddkwdk..",
        "..kWwwkkkkwwdk..",
        "...kwwwwwwwdk...",
        "...kwwwwwwddk...",
        "....kkddddkk....",
        "......kkkk......",
        "................",
        "................",
    ],
    'farmer': [
        "................",
        "....G..G..G.....",
        "...GgkGgkGgk....",
        "...gGkgGkgGk....",
        "...Ggk.Ggk.Ggk..",
        "....gGk.gGk.gk..",
        "....Ggk.Ggk.Gk..",
        "...kgk.kgk.kgk..",
        "..Nkmk.kmk.kmkN.",
        "..kNNk.kmk.kNNk.",
        "...kmmkkmkkmmk..",
        "....khhhhhhhk...",
        "....kGGGGGGGk...",
        ".....kmkmkmk....",
        ".....kmkmkmk....",
        "......k.k.k.....",
    ],
    'lumberer': [
        "..........kkk...",
        ".........kIIik..",
        "........kIiiijk.",
        ".......kjkIiijk.",
        "......kWk.kjjk..",
        ".....kWdk..kk...",
        "....kWdk........",
        "..kkkWdkkkkkk...",
        ".kLOLkkWWWWWWk..",
        "kLOlOLkwwwwwwwk.",
        "kOlLlOkwwdwwwwk.",
        "kLOlOLkwwwwwdwk.",
        "kLLOLLkwwwwwwwk.",
        ".kLLLkkddddddk..",
        "..kkkkkkkkkkk...",
        "................",
    ],
    'guard': [
        "................",
        "..kkkkkkkkkkkk..",
        "..kiIIIIIIIIik..",
        "..kIbbbbbbbbjk..",
        "..kIbbboobbbjk..",
        "..kIbbooOobbjk..",
        "..kIbooOOOobjk..",
        "..kIoOObbOOojk..",
        "..kIOObbbbOOjk..",
        "...kIbbbbbbjk...",
        "...kIbbbbbbjk...",
        "....kIbbbbjk....",
        "....kjcbbcjk....",
        ".....kjccjk.....",
        "......kjjk......",
        ".......kk.......",
    ],
    'courier': [
        "................",
        ".....kkkkkk.....",
        "....kl....lk....",
        "...kl......lk...",
        "..kkkkkkkkkkkk..",
        ".kLLLLLLLLLLLLk.",
        ".kLllllllllllLk.",
        ".kLllllkkllllLk.",
        ".klllllkGkllllk.",
        ".klllllkgklllk..",
        ".kllllllkklllk..",
        ".kLlllllllllldk.",
        ".kLlllllllllldk.",
        ".klllllllllldk..",
        "..kkkkkkkkkkkk..",
        "................",
    ],
    'baker': [
        "................",
        "................",
        "................",
        ".....kkkkkk.....",
        "...kkTTTTTTkk...",
        "..kTTTuTTuTTTk..",
        ".kTTTuTTuTTuTTk.",
        ".kTTuTTuTTuTTtk.",
        "kTTuTTuTTuTTttuk",
        "kTtTTuTTuTTtttuk",
        "kttttttttttttuuk",
        ".kttttttttttuuk.",
        "..kuuuuuuuuuuk..",
        "...kkkkkkkkkk...",
        "................",
        "................",
    ],
    'cook': [
        "......O..O......",
        ".....O..O..O....",
        "......O..O..O...",
        ".....O..O..O....",
        "..kkkkkkkkkkkk..",
        ".kXXXXXXXXXXXXk.",
        "kkxtftTfttfTtxkk",
        "kXkxxxxxxxxxxkXk",
        "kkXXxxxxxxxxxxkk",
        ".kXxxxxxxxxxxxk.",
        ".kXxxxxxxxxxxxk.",
        ".kXxxxxxxxxxxxk.",
        "..kxxxxxxxxxxk..",
        "...kkkkkkkkkk...",
        "...kxk....kxk...",
        "...kk......kk...",
    ],
    'butcher': [
        "................",
        "................",
        ".kkkkkkkkk......",
        "kIIIIIIIIjk.....",
        "kIiiiiiiijk.....",
        "kIiiikiiijk.....",
        "kIiiiiiiijk.....",
        "kIiiiiiiijkkk...",
        "kjjjjjjjjjkWWk..",
        ".kkkkkkkkkkwWWk.",
        "..........kdwWWk",
        "...........kdwWk",
        "............kdwk",
        ".............kdk",
        "..............k.",
        "................",
    ],
    'smelter': [
        "................",
        ".....F....F.....",
        "....FfF..FfF....",
        "...FffF.FffF....",
        "...fFfFFfFff....",
        "..kkkkkkkkkkkk..",
        ".kSssssssssssSk.",
        ".ksSSSSSSSSSSsk.",
        ".ksSkkkkkkkkSsk.",
        ".ksSkfFFFFfkSsk.",
        ".ksSkffFFffkSsk.",
        ".ksSkkkkkkkkSsk.",
        ".ksssssssssssSk.",
        ".kSSSSSSSSSSSSk.",
        "..kkkkkkkkkkkk..",
        "................",
    ],
    'smith': [
        "................",
        "................",
        "................",
        ".kkkkkkkkkkkkk..",
        "kXXXXXXXXXXXXXk.",
        "kkXxxxxxxxxxxxk.",
        ".kkXxxxxxxxxxk..",
        "...kkkxxxxxkk...",
        ".....kXxxxk.....",
        ".....kXxxxk.....",
        "....kXxxxxxk....",
        "...kXxxxxxxxk...",
        "..kXXXXXXXXXXk..",
        "..kxxxxxxxxxxk..",
        "..kkkkkkkkkkkk..",
        "................",
    ],
    'sawyer': [
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "...........kkkk.",
        "kkkkkkkkkkkWWWWk",
        "kIIIIIIIIIkWkkwk",
        "kiiiiiiiiikWk.wk",
        "kiiiiiiiiikWkkwk",
        "kjijijijijkwwwdk",
        ".kjkjkjkjkkkkkk.",
        "..k.k.k.k.......",
        "................",
        "................",
    ],
    'carpenter': [
        "................",
        "...kkkkkkkkkk...",
        "..kIIIIIIIIIjk..",
        ".kIiiiiiiiiijk..",
        ".kik.kjWdkjjjk..",
        "..k..kkWdkkkk...",
        "......kWdk......",
        "......kWdk......",
        "......kWdk......",
        "......kWdk......",
        "......kWdk......",
        "......klLk......",
        "......kLlk......",
        "......klLk......",
        "......kkkk......",
        "................",
    ],
    'mason': [
        ".........kk.....",
        "........kIjk....",
        ".......kIijk....",
        "......kIijk.....",
        ".....kkijk......",
        "....kdkjk.......",
        "...kWdkk........",
        "..kWdk..........",
        ".kWdk.kkkkkkk...",
        ".kdk.kOOOOOOsk..",
        "..k.kOssssssSk..",
        "...kkkkkkkkkkkk.",
        "..kOOOOOsOOOOOsk",
        "..kssssSkssssssk",
        "..kSSSSSkSSSSSSk",
        "...kkkkkkkkkkkk.",
    ],
    'fletcher': [
        "................",
        "....k...k...k...",
        "...kIk.kIk.kIk..",
        "...kjk.kjk.kjk..",
        "....d...d...d...",
        "....d...d...d...",
        "....d...d...d...",
        "...kkkkkkkkkkk..",
        "...kLLLLLLLLLk..",
        "...klllllllllk..",
        "...kkkkkkkkkkk..",
        "....d...d...d...",
        "...RdR.RdR.RdR..",
        "...RdR.RdR.RdR..",
        "...odo.odo.odo..",
        "................",
    ],
    'weaver': [
        "................",
        "...kkkkkkkkkk...",
        "..kWWWWWWWWwdk..",
        "...kkkkkkkkkk...",
        "....kRrRrRrk....",
        "....krRrRrRk....",
        "....kRrRrRrk....",
        "....krRrRrRk....",
        "....kRrRrRrk....",
        "....krRrRrRkr...",
        "....kRrRrRrk.r..",
        "....krRrRrRk..r.",
        "...kkkkkkkkkk.r.",
        "..kWWWWWWWWwdkr.",
        "...kkkkkkkkkk...",
        "................",
    ],
    'tanner': [
        "................",
        "...kk......kk...",
        "..kLlk....kLlk..",
        "..kllkkkkkklLk..",
        "...klLLLLLLllk..",
        "...kLLlllllLk...",
        "..kLLllllllllk..",
        ".kLLlllllllllk..",
        ".klLllllllllk...",
        "..klllllllllk...",
        "..kLlllllllllk..",
        ".kLLllllllllllk.",
        ".klllkkkkkklllk.",
        ".kllk......kllk.",
        "..kk........kk..",
        "................",
    ],
    'miner': [
        "................",
        "....kkkkkk......",
        "..kkIIIIIIkk....",
        ".kIijjjjjjiIk...",
        "kIjk.kWk..kjIk..",
        "kjk..kWdk..kjk..",
        "kk...kWdk...kk..",
        ".....kkWdk......",
        "......kWdk......",
        "......kkWdk.....",
        ".......kWdk.....",
        ".......kkWdk....",
        "........kWdk....",
        "........kkWdk...",
        ".........kddk...",
        "..........kk....",
    ],
    'innkeeper': [
        "................",
        "...kkkkkkk......",
        "..koooooooko....",
        "..koOoooOook....",
        "..kkkkkkkkkk....",
        "..kWwwWwwWwkkk..",
        "..kjjjjjjjjkWWk.",
        "..kWwwWwwWwk..wk",
        "..kWwwWwwWwk..wk",
        "..kWwwWwwWwk..wk",
        "..kjjjjjjjjkwdk.",
        "..kWwwWwwWwkkk..",
        "..kddddddddk....",
        "...kkkkkkkk.....",
        "................",
        "................",
    ],
    'scholar': [
        "................",
        "..kkkkkkkkkkk...",
        ".krRRRRRRRRRgk..",
        ".krRRRRgRRRRgk..",
        ".krRRRggGRRRgk..",
        ".krRRRRgRRRRgk..",
        ".krRRRRgRRRRgk..",
        ".krRRRRRRRRRgk..",
        ".krrrrrrrrrrgk..",
        ".kreeeeeeeeegk..",
        ".krkkkkkkkkkkk..",
        ".krkoooooooook..",
        ".krkOOOOOOOOOk..",
        ".kekkkkkkkkkkk..",
        "..kkkkkkkkkkk...",
        "................",
    ],
    'miller': [
        "................",
        ".......kk.......",
        "......kOOk......",
        ".....kkOOkk.....",
        "....kOOOOOOk....",
        "...kOooooooOk...",
        "..kOoooooooooOk.",
        "..kOoookkooooOk.",
        "..kOookGGkoooOk.",
        "..kOookGGkoooOk.",
        "..kOooookkoooOk.",
        "..kOoooooooooOk.",
        "..kOOoooooooOOk.",
        "...kOOOOOOOOOk..",
        "....kkkkkkkkk...",
        "................",
    ],
    'brewer': [
        "................",
        "....kkkkkkkk....",
        "...kWWWWWWwwk...",
        "..kjjjjjjjjjjk..",
        "..kWwwWwwWwwdk..",
        ".kWWwwWwwWwwwdk.",
        ".kWWwwWwwWwwwdk.",
        ".kjjjjjjjjjjjjk.",
        ".kWWwwWwwWwwwdk.",
        ".kWWwwWwwWwwwdk.",
        "..kWwwWwwWwwdk..",
        "..kjjjjjjjjjjk..",
        "...kwwwwwwwdk...",
        "....kkkkkkkk....",
        "................",
        "................",
    ],
    'archer': [
        "................",
        "......kkk.......",
        ".....kWWdk......",
        "....kWdkok......",
        "...kWdk.o.......",
        "...kWk..o.......",
        "..kWdk..o...kk..",
        ".kkWkkkkokkkkIk.",
        "kRRWwwwwowwwwIIk",
        ".kkWkkkkokkkkIk.",
        "..kWdk..o...kk..",
        "...kWk..o.......",
        "...kWdk.o.......",
        "....kWdkok......",
        ".....kWWdk......",
        "......kkk.......",
    ],
    'armourer': [
        "................",
        "..kkk......kkk..",
        ".kIiik....kIijk.",
        ".kIiiikkkkkiijk.",
        ".kIiiIIIIIIiijk.",
        "..kkIiiiiiiijk..",
        "...kIiiiiiiijk..",
        "...kIiikkiiijk..",
        "...kIiiiiiiijk..",
        "...kIiiiiiiijk..",
        "...kIjjjjjjjjk..",
        "...kIiiiiiiijk..",
        "...kIiiiiiiijk..",
        "....kjjjjjjjk...",
        ".....kkkkkkk....",
        "................",
    ],
    'herder': [
        "................",
        "....kk.kk.kk....",
        "...kook.kook....",
        "..koOooookoOk...",
        ".kooOkkkkkoOok..",
        "kkkoksssskokkk..",
        "kSSkssssssksSk..",
        ".kkksossosskk...",
        "..kossssssook...",
        "..koskssksok....",
        "..kossssssOok...",
        "...kosSSsoOk....",
        "...kooSSoook....",
        "....kOoooOk.....",
        ".....kkkkk......",
        "................",
    ],
    'fisher': [
        "..............k.",
        ".............kjk",
        ".............kjk",
        ".............kjk",
        "..kkk........kjk",
        ".kBBbk....kk.kjk",
        "kBbbbbk..kBk.kjk",
        "kbBbkbbkkBbk.kjk",
        "kbbbbbbbbbk..kjk",
        "kcbbbbbbbck..kjk",
        ".kccbbbbcBbk.kjk",
        "..kkccckkkBk.kjk",
        "....kkk...kk.kjk",
        "..........kk.kjk",
        "..........kjkkjk",
        "...........kjjk.",
    ],
    'hunter': [
        "................",
        ".kk.............",
        "kGGk............",
        "kgGhk...........",
        ".kghk...........",
        ".kghhk..........",
        "..kghhk......kk.",
        "..kgghhkkkkkkGk.",
        "...kggghhhhhhgk.",
        "....kgggggggggk.",
        ".....kkggggghk..",
        ".......kkkkkk...",
        "......kl....lk..",
        ".....kl......lk.",
        "......kkkkkkkk..",
        "................",
    ],
    'mayor': [
        "................",
        ".....kkkkkk.....",
        "...kkrRRRRrkk...",
        "..krRRRgRRRrk...",
        "..kRRgRgRgRRk...",
        ".krRRgggggRRrk..",
        ".kRRRRgGgRRRRk..",
        ".kRRgggggggRRk..",
        ".krRRRRgRRRRrk..",
        "..kRRRggGRRRk...",
        "..krrRRRRRrrk...",
        "...kkrrrrrkk....",
        "....krk.kek.....",
        "...krrk.kerk....",
        "...kek...kek....",
        "....k.....k.....",
    ],
    'trader': [
        ".......kk.......",
        "......kGGk......",
        ".kkkkkkghkkkkkk.",
        ".kGgggggggggghk.",
        ".kkkkkkghkkkkkk.",
        ".k.k...kgk..k.k.",
        "k...k..kgk.k...k",
        "k...k..kgk.k...k",
        "kGggGk.kgk.kGgGk",
        ".khhk..kgk..khk.",
        "..kk...kgk...kk.",
        "......kgGgk.....",
        ".....kggggGk....",
        "....khhhhhhhk...",
        "....kkkkkkkkk...",
        "................",
    ],
    'spearman': [
        ".............kk.",
        "............kIIk",
        "...........kIiIk",
        "..........kIijk.",
        ".........kkjjk..",
        "........kRkkk...",
        ".......kWRk.....",
        "......kWdk......",
        ".....kWdk.......",
        "....kWdk........",
        "...kWdk.........",
        "..kWdk..........",
        ".kWdk...........",
        "kWdk............",
        "kdk.............",
        ".k..............",
    ],
    'longswordsman': [
        ".......kk.......",
        "......kIjk......",
        "......kIjk......",
        "......kIjk......",
        "......kIjk......",
        "......kIjk......",
        "......kIjk......",
        "......kIjk......",
        "......kIjk......",
        "..kkkkkIjkkkkk..",
        "..kgGGGggggghk..",
        "..kkkkkWdkkkkk..",
        "......klLk......",
        "......kLlk......",
        "......kgGk......",
        ".......kk.......",
    ],
    'healer': [
        "................",
        ".....kkkkkk.....",
        ".....kOOOOk.....",
        "......kOOk......",
        "......kook......",
        "....kkkookkk....",
        "...kooooooook...",
        "..kooookkooook..",
        "..koookRRkoook..",
        "..kokkkRRkkkok..",
        "..kokRRRRRRkok..",
        "..kokkkRRkkkok..",
        "..koookRRkoook..",
        "...kooookkook...",
        "....kkkkkkkk....",
        "................",
    ],
    'rune_mage': [
        "................",
        "......kkkk......",
        "....kkSSSSkk....",
        "...kSSsssssSk...",
        "..kSsspPPpssSk..",
        "..kSsspqPqssSk..",
        ".kSsssspPsssSSk.",
        ".kSssspPsssssSk.",
        ".kSsssPpsssssSk.",
        ".kSssspPpPssSSk.",
        ".kSsssssPpssSSk.",
        "..kSssssssssSk..",
        "..kSSssssssSSk..",
        "...kkSSSSSSkk...",
        ".....kkkkkk.....",
        "................",
    ],
    # Builder: a mason's trowel over two laid bricks.
    'builder': [
        "................",
        "..........kk....",
        ".........kWdk...",
        "........kWdk....",
        ".......kWdk.....",
        "....kkkkdk......",
        "...kIIIIjk......",
        "..kIiiiijk......",
        ".kIiiiijk.......",
        ".kjjjjjk........",
        "..kkkkk.........",
        "..kkkkkkkkkkkkk.",
        ".krRRRrkrRRRRrk.",
        ".keeeeekeeeeeek.",
        "..kkkkkkkkkkkk..",
        "................",
    ],
}


def validate():
    for key, grid in ICONS.items():
        if len(grid) != 16:
            raise SystemExit(f"{key}: {len(grid)} rows")
        for n, row in enumerate(grid):
            if len(row) != 16:
                raise SystemExit(f"{key} row {n}: {len(row)} cols -> {row!r}")
            for ch in row:
                if ch not in PALETTE:
                    raise SystemExit(f"{key} row {n}: unknown colour {ch!r}")


def image(grid):
    img = Image.new('RGBA', (16, 16), (0, 0, 0, 0))
    px = img.load()
    for y, row in enumerate(grid):
        for x, ch in enumerate(row):
            c = PALETTE[ch]
            if c is not None:
                px[x, y] = c + (255,)
    return img


def main():
    validate()
    root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    out = os.path.join(root, 'src', 'main', 'resources', 'assets', 'hearthstead', 'textures', 'gui', 'job')
    os.makedirs(out, exist_ok=True)
    images = {}
    for key, grid in ICONS.items():
        img = image(grid)
        img.save(os.path.join(out, key + '.png'))
        images[key] = img
    if '--preview' in sys.argv:
        dest = sys.argv[sys.argv.index('--preview') + 1]
        keys = list(ICONS)
        cols = 8
        rows = (len(keys) + cols - 1) // cols
        cell = 16 * 6 + 8
        sheet = Image.new('RGBA', (cols * cell, rows * cell), (231, 221, 200, 255))
        for n, key in enumerate(keys):
            cx, cy = (n % cols) * cell, (n // cols) * cell
            big = images[key].resize((16 * 4, 16 * 4), Image.NEAREST)
            sheet.alpha_composite(big, (cx + 4, cy + 4))
            sheet.alpha_composite(images[key].resize((32, 32), Image.NEAREST), (cx + 70, cy + 4))
            sheet.alpha_composite(images[key], (cx + 70, cy + 40))
        sheet.save(dest)
    print(f"wrote {len(ICONS)} icons to {out}")


if __name__ == '__main__':
    main()
