package com.hearthstead.client.model;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

import static net.minecraft.client.animation.AnimationChannel.Interpolations.CATMULLROM;
import static net.minecraft.client.animation.AnimationChannel.Targets.POSITION;
import static net.minecraft.client.animation.AnimationChannel.Targets.ROTATION;

/**
 * HUNTER v2 (owner 2026-09-26, full rework; tools/blender/pipeline/clips/roles/hunter.py). The
 * authored JSON replaces these on the motion engine; these vanilla-path fallbacks are GENERATED from it
 * (anim-overkill/gen_hunterfallbacks.py) and fix the
 * length/loop contract. All are absolute full-body clips: SettlerModel resets first.
 */
public final class HunterMotionAnimations {
    private HunterMotionAnimations() {
    }

    /** Hunter v2: stalk-ready, stationary (TRACKING_GAME, not moving): crouched, look and listen, 4.00 s loop. */
    public static final AnimationDefinition HUNTER_READY = AnimationDefinition.Builder
        .withLength(4F).looping()
        .addAnimation("root", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 6F, 0F), CATMULLROM),
            new Keyframe(0.25F, KeyframeAnimations.degreeVec(0F, 6F, 0F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(0F, 6F, 0F), CATMULLROM),
            new Keyframe(0.75F, KeyframeAnimations.degreeVec(0F, 6F, 0F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.degreeVec(0F, 6F, 0F), CATMULLROM),
            new Keyframe(1.25F, KeyframeAnimations.degreeVec(0F, 6F, 0F), CATMULLROM),
            new Keyframe(1.5F, KeyframeAnimations.degreeVec(0F, 6F, 0F), CATMULLROM),
            new Keyframe(1.75F, KeyframeAnimations.degreeVec(0F, 6F, 0F), CATMULLROM),
            new Keyframe(2F, KeyframeAnimations.degreeVec(0F, 6F, 0F), CATMULLROM),
            new Keyframe(2.25F, KeyframeAnimations.degreeVec(0F, 6F, 0F), CATMULLROM),
            new Keyframe(2.5F, KeyframeAnimations.degreeVec(0F, 6F, 0F), CATMULLROM),
            new Keyframe(2.75F, KeyframeAnimations.degreeVec(0F, 6F, 0F), CATMULLROM),
            new Keyframe(3F, KeyframeAnimations.degreeVec(0F, 6F, 0F), CATMULLROM),
            new Keyframe(3.25F, KeyframeAnimations.degreeVec(0F, 6F, 0F), CATMULLROM),
            new Keyframe(3.5F, KeyframeAnimations.degreeVec(0F, 6F, 0F), CATMULLROM),
            new Keyframe(3.75F, KeyframeAnimations.degreeVec(0F, 6F, 0F), CATMULLROM),
            new Keyframe(4F, KeyframeAnimations.degreeVec(0F, 6F, 0F), CATMULLROM)))
        .addAnimation("root", new AnimationChannel(POSITION,
            new Keyframe(0F, KeyframeAnimations.posVec(0F, -2.4F, 0.8F), CATMULLROM),
            new Keyframe(0.25F, KeyframeAnimations.posVec(0F, -2.41F, 0.8F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.posVec(0F, -2.44F, 0.8F), CATMULLROM),
            new Keyframe(0.75F, KeyframeAnimations.posVec(0F, -2.47F, 0.8F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.posVec(0F, -2.53F, 0.8F), CATMULLROM),
            new Keyframe(1.25F, KeyframeAnimations.posVec(0F, -2.58F, 0.8F), CATMULLROM),
            new Keyframe(1.5F, KeyframeAnimations.posVec(0F, -2.62F, 0.8F), CATMULLROM),
            new Keyframe(1.75F, KeyframeAnimations.posVec(0F, -2.64F, 0.8F), CATMULLROM),
            new Keyframe(2F, KeyframeAnimations.posVec(0F, -2.64F, 0.8F), CATMULLROM),
            new Keyframe(2.25F, KeyframeAnimations.posVec(0F, -2.63F, 0.8F), CATMULLROM),
            new Keyframe(2.5F, KeyframeAnimations.posVec(0F, -2.61F, 0.8F), CATMULLROM),
            new Keyframe(2.75F, KeyframeAnimations.posVec(0F, -2.58F, 0.8F), CATMULLROM),
            new Keyframe(3F, KeyframeAnimations.posVec(0F, -2.53F, 0.8F), CATMULLROM),
            new Keyframe(3.25F, KeyframeAnimations.posVec(0F, -2.47F, 0.8F), CATMULLROM),
            new Keyframe(3.5F, KeyframeAnimations.posVec(0F, -2.44F, 0.8F), CATMULLROM),
            new Keyframe(3.75F, KeyframeAnimations.posVec(0F, -2.41F, 0.8F), CATMULLROM),
            new Keyframe(4F, KeyframeAnimations.posVec(0F, -2.4F, 0.8F), CATMULLROM)))
        .addAnimation("torso", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(22F, 8F, 0F), CATMULLROM),
            new Keyframe(0.25F, KeyframeAnimations.degreeVec(22F, 8.6F, 0F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(22F, 10.23F, 0F), CATMULLROM),
            new Keyframe(0.75F, KeyframeAnimations.degreeVec(22F, 11.81F, 0F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.degreeVec(22F, 12.9F, 0F), CATMULLROM),
            new Keyframe(1.25F, KeyframeAnimations.degreeVec(22F, 12.63F, 0F), CATMULLROM),
            new Keyframe(1.5F, KeyframeAnimations.degreeVec(22F, 10.69F, 0F), CATMULLROM),
            new Keyframe(1.75F, KeyframeAnimations.degreeVec(22F, 7.81F, 0F), CATMULLROM),
            new Keyframe(2F, KeyframeAnimations.degreeVec(22F, 5.81F, 0F), CATMULLROM),
            new Keyframe(2.25F, KeyframeAnimations.degreeVec(22F, 4.84F, 0F), CATMULLROM),
            new Keyframe(2.5F, KeyframeAnimations.degreeVec(22F, 5.5F, 0F), CATMULLROM),
            new Keyframe(2.75F, KeyframeAnimations.degreeVec(22F, 6.53F, 0F), CATMULLROM),
            new Keyframe(3F, KeyframeAnimations.degreeVec(22F, 7.49F, 0F), CATMULLROM),
            new Keyframe(3.25F, KeyframeAnimations.degreeVec(22F, 7.78F, 0F), CATMULLROM),
            new Keyframe(3.5F, KeyframeAnimations.degreeVec(22F, 7.9F, 0F), CATMULLROM),
            new Keyframe(3.75F, KeyframeAnimations.degreeVec(22F, 7.96F, 0F), CATMULLROM),
            new Keyframe(4F, KeyframeAnimations.degreeVec(22F, 8F, 0F), CATMULLROM)))
        .addAnimation("head", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(-20F, -10F, 0F), CATMULLROM),
            new Keyframe(0.25F, KeyframeAnimations.degreeVec(-20.37F, -9.99F, 0F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(-21.35F, -9.86F, 0F), CATMULLROM),
            new Keyframe(0.75F, KeyframeAnimations.degreeVec(-22.31F, -0.48F, 0F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.degreeVec(-22.94F, 14.29F, 0F), CATMULLROM),
            new Keyframe(1.25F, KeyframeAnimations.degreeVec(-22.64F, 15.44F, 0F), CATMULLROM),
            new Keyframe(1.5F, KeyframeAnimations.degreeVec(-21.51F, 14.3F, 0F), CATMULLROM),
            new Keyframe(1.75F, KeyframeAnimations.degreeVec(-19.79F, 10.71F, 0F), CATMULLROM),
            new Keyframe(2F, KeyframeAnimations.degreeVec(-18.4F, -32F, 0F), CATMULLROM),
            new Keyframe(2.25F, KeyframeAnimations.degreeVec(-18.01F, -31.01F, -6.92F), CATMULLROM),
            new Keyframe(2.5F, KeyframeAnimations.degreeVec(-18.14F, -30.18F, -6.09F), CATMULLROM),
            new Keyframe(2.75F, KeyframeAnimations.degreeVec(-18.43F, -29.73F, -4.15F), CATMULLROM),
            new Keyframe(3F, KeyframeAnimations.degreeVec(-18.82F, -20.04F, 0.02F), CATMULLROM),
            new Keyframe(3.25F, KeyframeAnimations.degreeVec(-19.24F, -10.22F, 0F), CATMULLROM),
            new Keyframe(3.5F, KeyframeAnimations.degreeVec(-19.5F, -9.99F, 0F), CATMULLROM),
            new Keyframe(3.75F, KeyframeAnimations.degreeVec(-19.79F, -9.99F, 0F), CATMULLROM),
            new Keyframe(4F, KeyframeAnimations.degreeVec(-20F, -10F, 0F), CATMULLROM)))
        .addAnimation("right_arm", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(-131.93F, -29.64F, 107.93F), CATMULLROM),
            new Keyframe(0.25F, KeyframeAnimations.degreeVec(-131.76F, -29.55F, 107.83F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(-131.5F, -29.41F, 107.68F), CATMULLROM),
            new Keyframe(0.75F, KeyframeAnimations.degreeVec(-131.23F, -29.26F, 107.52F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.degreeVec(-131.03F, -29.15F, 107.41F), CATMULLROM),
            new Keyframe(1.25F, KeyframeAnimations.degreeVec(-131F, -29.14F, 107.39F), CATMULLROM),
            new Keyframe(1.5F, KeyframeAnimations.degreeVec(-131.31F, -29.31F, 107.57F), CATMULLROM),
            new Keyframe(1.75F, KeyframeAnimations.degreeVec(-131.74F, -29.54F, 107.82F), CATMULLROM),
            new Keyframe(2F, KeyframeAnimations.degreeVec(-131.92F, -29.64F, 107.92F), CATMULLROM),
            new Keyframe(2.25F, KeyframeAnimations.degreeVec(-131.79F, -29.56F, 107.85F), CATMULLROM),
            new Keyframe(2.5F, KeyframeAnimations.degreeVec(-131.52F, -29.42F, 107.69F), CATMULLROM),
            new Keyframe(2.75F, KeyframeAnimations.degreeVec(-131.25F, -29.27F, 107.53F), CATMULLROM),
            new Keyframe(3F, KeyframeAnimations.degreeVec(-131.11F, -29.2F, 107.45F), CATMULLROM),
            new Keyframe(3.25F, KeyframeAnimations.degreeVec(-131.19F, -29.24F, 107.5F), CATMULLROM),
            new Keyframe(3.5F, KeyframeAnimations.degreeVec(-131.44F, -29.38F, 107.65F), CATMULLROM),
            new Keyframe(3.75F, KeyframeAnimations.degreeVec(-131.73F, -29.53F, 107.81F), CATMULLROM),
            new Keyframe(4F, KeyframeAnimations.degreeVec(-131.93F, -29.64F, 107.93F), CATMULLROM)))
        .addAnimation("left_arm", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(-39.47F, 9.09F, 0F), CATMULLROM),
            new Keyframe(0.25F, KeyframeAnimations.degreeVec(-39.68F, 9.09F, 0F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(-40F, 9.09F, 0F), CATMULLROM),
            new Keyframe(0.75F, KeyframeAnimations.degreeVec(-40.31F, 9.09F, 0F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.degreeVec(-40.46F, 9.09F, 0F), CATMULLROM),
            new Keyframe(1.25F, KeyframeAnimations.degreeVec(-40.33F, 9.09F, 0F), CATMULLROM),
            new Keyframe(1.5F, KeyframeAnimations.degreeVec(-39.98F, 9.09F, 0F), CATMULLROM),
            new Keyframe(1.75F, KeyframeAnimations.degreeVec(-39.62F, 9.09F, 0F), CATMULLROM),
            new Keyframe(2F, KeyframeAnimations.degreeVec(-39.47F, 9.09F, 0F), CATMULLROM),
            new Keyframe(2.25F, KeyframeAnimations.degreeVec(-39.61F, 9.09F, 0F), CATMULLROM),
            new Keyframe(2.5F, KeyframeAnimations.degreeVec(-39.89F, 9.09F, 0F), CATMULLROM),
            new Keyframe(2.75F, KeyframeAnimations.degreeVec(-40.16F, 9.09F, 0F), CATMULLROM),
            new Keyframe(3F, KeyframeAnimations.degreeVec(-40.26F, 9.09F, 0F), CATMULLROM),
            new Keyframe(3.25F, KeyframeAnimations.degreeVec(-40.14F, 9.09F, 0F), CATMULLROM),
            new Keyframe(3.5F, KeyframeAnimations.degreeVec(-39.9F, 9.09F, 0F), CATMULLROM),
            new Keyframe(3.75F, KeyframeAnimations.degreeVec(-39.64F, 9.09F, 0F), CATMULLROM),
            new Keyframe(4F, KeyframeAnimations.degreeVec(-39.46F, 9.09F, 0F), CATMULLROM)))
        .addAnimation("right_leg", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(-39.65F, 1.96F, 4.44F), CATMULLROM),
            new Keyframe(0.25F, KeyframeAnimations.degreeVec(-39.83F, 1.96F, 4.45F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(-40.11F, 1.96F, 4.47F), CATMULLROM),
            new Keyframe(0.75F, KeyframeAnimations.degreeVec(-40.43F, 1.96F, 4.5F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.degreeVec(-40.77F, 1.96F, 4.53F), CATMULLROM),
            new Keyframe(1.25F, KeyframeAnimations.degreeVec(-41.09F, 1.96F, 4.55F), CATMULLROM),
            new Keyframe(1.5F, KeyframeAnimations.degreeVec(-41.33F, 1.96F, 4.57F), CATMULLROM),
            new Keyframe(1.75F, KeyframeAnimations.degreeVec(-41.46F, 1.96F, 4.58F), CATMULLROM),
            new Keyframe(2F, KeyframeAnimations.degreeVec(-41.45F, 1.96F, 4.58F), CATMULLROM),
            new Keyframe(2.25F, KeyframeAnimations.degreeVec(-41.33F, 1.96F, 4.57F), CATMULLROM),
            new Keyframe(2.5F, KeyframeAnimations.degreeVec(-41.13F, 1.96F, 4.55F), CATMULLROM),
            new Keyframe(2.75F, KeyframeAnimations.degreeVec(-40.87F, 1.96F, 4.53F), CATMULLROM),
            new Keyframe(3F, KeyframeAnimations.degreeVec(-40.59F, 1.96F, 4.51F), CATMULLROM),
            new Keyframe(3.25F, KeyframeAnimations.degreeVec(-40.29F, 1.96F, 4.49F), CATMULLROM),
            new Keyframe(3.5F, KeyframeAnimations.degreeVec(-40.02F, 1.96F, 4.47F), CATMULLROM),
            new Keyframe(3.75F, KeyframeAnimations.degreeVec(-39.8F, 1.96F, 4.45F), CATMULLROM),
            new Keyframe(4F, KeyframeAnimations.degreeVec(-39.65F, 1.96F, 4.44F), CATMULLROM)))
        .addAnimation("left_leg", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(-52.09F, -13.97F, -0.56F), CATMULLROM),
            new Keyframe(0.25F, KeyframeAnimations.degreeVec(-52.09F, -13.97F, -0.56F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(-52.45F, -13.97F, -0.57F), CATMULLROM),
            new Keyframe(0.75F, KeyframeAnimations.degreeVec(-52.86F, -13.97F, -0.57F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.degreeVec(-53.36F, -13.97F, -0.57F), CATMULLROM),
            new Keyframe(1.25F, KeyframeAnimations.degreeVec(-53.86F, -13.97F, -0.57F), CATMULLROM),
            new Keyframe(1.5F, KeyframeAnimations.degreeVec(-54.25F, -13.97F, -0.58F), CATMULLROM),
            new Keyframe(1.75F, KeyframeAnimations.degreeVec(-54.62F, -13.97F, -0.58F), CATMULLROM),
            new Keyframe(2F, KeyframeAnimations.degreeVec(-54.75F, -13.97F, -0.58F), CATMULLROM),
            new Keyframe(2.25F, KeyframeAnimations.degreeVec(-54.49F, -13.97F, -0.58F), CATMULLROM),
            new Keyframe(2.5F, KeyframeAnimations.degreeVec(-54.22F, -13.97F, -0.58F), CATMULLROM),
            new Keyframe(2.75F, KeyframeAnimations.degreeVec(-53.87F, -13.97F, -0.58F), CATMULLROM),
            new Keyframe(3F, KeyframeAnimations.degreeVec(-53.46F, -13.97F, -0.57F), CATMULLROM),
            new Keyframe(3.25F, KeyframeAnimations.degreeVec(-53.05F, -13.97F, -0.57F), CATMULLROM),
            new Keyframe(3.5F, KeyframeAnimations.degreeVec(-52.65F, -13.97F, -0.57F), CATMULLROM),
            new Keyframe(3.75F, KeyframeAnimations.degreeVec(-52.32F, -13.97F, -0.56F), CATMULLROM),
            new Keyframe(4F, KeyframeAnimations.degreeVec(-52.09F, -13.97F, -0.56F), CATMULLROM)))
        .build();

    /** Hunter v2: the crouched stalk (locomotion while TRACKING_GAME; WALK's stride), 1.00 s loop. */
    public static final AnimationDefinition HUNTER_STALK = AnimationDefinition.Builder
        .withLength(1F).looping()
        .addAnimation("root", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 3.6F, 0F), CATMULLROM),
            new Keyframe(0.25F, KeyframeAnimations.degreeVec(0F, 6.12F, 0F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(0F, 8.39F, 0F), CATMULLROM),
            new Keyframe(0.75F, KeyframeAnimations.degreeVec(0F, 5.87F, 0F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.degreeVec(0F, 3.6F, 0F), CATMULLROM)))
        .addAnimation("root", new AnimationChannel(POSITION,
            new Keyframe(0F, KeyframeAnimations.posVec(0F, -3.21F, 0.8F), CATMULLROM),
            new Keyframe(0.25F, KeyframeAnimations.posVec(0F, -2.53F, 0.8F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.posVec(0F, -3.21F, 0.8F), CATMULLROM),
            new Keyframe(0.75F, KeyframeAnimations.posVec(0F, -2.53F, 0.8F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.posVec(0F, -3.21F, 0.8F), CATMULLROM)))
        .addAnimation("torso", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(18F, 8F, 0F), CATMULLROM),
            new Keyframe(0.25F, KeyframeAnimations.degreeVec(18F, 5.4F, 0.83F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(18F, 7.91F, 0.03F), CATMULLROM),
            new Keyframe(0.75F, KeyframeAnimations.degreeVec(18F, 10.55F, -0.82F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.degreeVec(18F, 8F, 0F), CATMULLROM)))
        .addAnimation("head", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(-19.16F, -10F, 0F), CATMULLROM),
            new Keyframe(0.25F, KeyframeAnimations.degreeVec(-20.86F, -7.94F, 0F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(-19.32F, -6.04F, 0F), CATMULLROM),
            new Keyframe(0.75F, KeyframeAnimations.degreeVec(-20.86F, -8.05F, 0F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.degreeVec(-19.16F, -10F, 0F), CATMULLROM)))
        .addAnimation("right_arm", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(-131.89F, -29.28F, 107.54F), CATMULLROM),
            new Keyframe(0.25F, KeyframeAnimations.degreeVec(-131.49F, -29.29F, 107.56F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(-131.92F, -29.28F, 107.54F), CATMULLROM),
            new Keyframe(0.75F, KeyframeAnimations.degreeVec(-132.33F, -29.26F, 107.53F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.degreeVec(-131.89F, -29.28F, 107.54F), CATMULLROM)))
        .addAnimation("left_arm", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(-39.47F, 9.09F, 0F), CATMULLROM),
            new Keyframe(0.25F, KeyframeAnimations.degreeVec(-39.44F, 9.09F, 0F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(-39.46F, 9.09F, 0F), CATMULLROM),
            new Keyframe(0.75F, KeyframeAnimations.degreeVec(-39.49F, 9.09F, 0F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.degreeVec(-39.47F, 9.09F, 0F), CATMULLROM)))
        .addAnimation("right_leg", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(-70.53F, 4.37F, -0.83F), CATMULLROM),
            new Keyframe(0.25F, KeyframeAnimations.degreeVec(-52.2F, 1.96F, 4.24F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(-18.28F, -0.41F, 10.88F), CATMULLROM),
            new Keyframe(0.75F, KeyframeAnimations.degreeVec(-64.26F, 1.94F, 11.03F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.degreeVec(-70.53F, 4.37F, -0.83F), CATMULLROM)))
        .addAnimation("left_leg", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(-11.03F, -11.34F, -11.5F), CATMULLROM),
            new Keyframe(0.25F, KeyframeAnimations.degreeVec(-55.37F, -13.66F, -12.37F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(-70.51F, -16.37F, 0.13F), CATMULLROM),
            new Keyframe(0.75F, KeyframeAnimations.degreeVec(-49.21F, -13.91F, -4.91F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.degreeVec(-11.03F, -11.34F, -11.5F), CATMULLROM)))
        .build();

    /** Hunter v2: WORK_HUNT draw, aim, RELEASE 0.70 (tick 14), follow-through, a new arrow nocked by 1.12; 1.20 s = 24 ticks. */
    public static final AnimationDefinition HUNTER_DRAW = AnimationDefinition.Builder
        .withLength(1.2F)
        .addAnimation("root", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 6F, 0F), CATMULLROM),
            new Keyframe(0.1F, KeyframeAnimations.degreeVec(0F, 6.41F, 0F), CATMULLROM),
            new Keyframe(0.2F, KeyframeAnimations.degreeVec(0F, 17.1F, 0F), CATMULLROM),
            new Keyframe(0.3F, KeyframeAnimations.degreeVec(0F, 46F, 0F), CATMULLROM),
            new Keyframe(0.4F, KeyframeAnimations.degreeVec(0F, 46F, 0F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(0F, 46F, 0F), CATMULLROM),
            new Keyframe(0.6F, KeyframeAnimations.degreeVec(0F, 46F, 0F), CATMULLROM),
            new Keyframe(0.7F, KeyframeAnimations.degreeVec(0F, 46F, 0F), CATMULLROM),
            new Keyframe(0.8F, KeyframeAnimations.degreeVec(0F, 46.02F, 0F), CATMULLROM),
            new Keyframe(0.9F, KeyframeAnimations.degreeVec(0F, 42.83F, 0F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.degreeVec(0F, 17.69F, 0F), CATMULLROM),
            new Keyframe(1.1F, KeyframeAnimations.degreeVec(0F, 6.05F, 0F), CATMULLROM),
            new Keyframe(1.2F, KeyframeAnimations.degreeVec(0F, 6F, 0F), CATMULLROM)))
        .addAnimation("root", new AnimationChannel(POSITION,
            new Keyframe(0F, KeyframeAnimations.posVec(0F, -2.4F, 0.8F), CATMULLROM),
            new Keyframe(0.1F, KeyframeAnimations.posVec(0F, -2.37F, 0.77F), CATMULLROM),
            new Keyframe(0.2F, KeyframeAnimations.posVec(0F, -2.23F, 0.63F), CATMULLROM),
            new Keyframe(0.3F, KeyframeAnimations.posVec(0F, -1.8F, 0.2F), CATMULLROM),
            new Keyframe(0.4F, KeyframeAnimations.posVec(0F, -1.78F, 0.18F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.posVec(0F, -1.79F, 0.19F), CATMULLROM),
            new Keyframe(0.6F, KeyframeAnimations.posVec(0F, -1.8F, 0.2F), CATMULLROM),
            new Keyframe(0.7F, KeyframeAnimations.posVec(0F, -1.8F, 0.2F), CATMULLROM),
            new Keyframe(0.8F, KeyframeAnimations.posVec(0F, -1.8F, 0.2F), CATMULLROM),
            new Keyframe(0.9F, KeyframeAnimations.posVec(0F, -1.85F, 0.25F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.posVec(0F, -2.21F, 0.61F), CATMULLROM),
            new Keyframe(1.1F, KeyframeAnimations.posVec(0F, -2.41F, 0.81F), CATMULLROM),
            new Keyframe(1.2F, KeyframeAnimations.posVec(0F, -2.4F, 0.8F), CATMULLROM)))
        .addAnimation("torso", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(22F, 8F, 0F), CATMULLROM),
            new Keyframe(0.1F, KeyframeAnimations.degreeVec(21.88F, 8.16F, 0.15F), CATMULLROM),
            new Keyframe(0.2F, KeyframeAnimations.degreeVec(18.67F, 12.44F, 0.57F), CATMULLROM),
            new Keyframe(0.3F, KeyframeAnimations.degreeVec(10.09F, 24F, 1.16F), CATMULLROM),
            new Keyframe(0.4F, KeyframeAnimations.degreeVec(10.5F, 24F, 1.75F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(10.78F, 24F, 2.17F), CATMULLROM),
            new Keyframe(0.6F, KeyframeAnimations.degreeVec(10.96F, 24F, 2.44F), CATMULLROM),
            new Keyframe(0.7F, KeyframeAnimations.degreeVec(11F, 24F, 2.5F), CATMULLROM),
            new Keyframe(0.8F, KeyframeAnimations.degreeVec(10.88F, 24F, 1.46F), CATMULLROM),
            new Keyframe(0.9F, KeyframeAnimations.degreeVec(10.95F, 22.73F, 0.97F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.degreeVec(18.46F, 12.72F, 0.63F), CATMULLROM),
            new Keyframe(1.1F, KeyframeAnimations.degreeVec(22.01F, 7.98F, 0.2F), CATMULLROM),
            new Keyframe(1.2F, KeyframeAnimations.degreeVec(22F, 8F, 0F), CATMULLROM)))
        .addAnimation("head", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(-20F, -10F, 0F), CATMULLROM),
            new Keyframe(0.1F, KeyframeAnimations.degreeVec(-16.03F, -22.31F, 0.79F), CATMULLROM),
            new Keyframe(0.2F, KeyframeAnimations.degreeVec(0F, -72F, 4F), CATMULLROM),
            new Keyframe(0.3F, KeyframeAnimations.degreeVec(0F, -72F, 4F), CATMULLROM),
            new Keyframe(0.4F, KeyframeAnimations.degreeVec(0F, -72F, 4F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(0F, -72F, 4F), CATMULLROM),
            new Keyframe(0.6F, KeyframeAnimations.degreeVec(0F, -72F, 4F), CATMULLROM),
            new Keyframe(0.7F, KeyframeAnimations.degreeVec(0F, -72F, 4F), CATMULLROM),
            new Keyframe(0.8F, KeyframeAnimations.degreeVec(0F, -67.76F, 4F), CATMULLROM),
            new Keyframe(0.9F, KeyframeAnimations.degreeVec(-1.59F, -54.33F, 3.68F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.degreeVec(-14.15F, -4F, 1.17F), CATMULLROM),
            new Keyframe(1.1F, KeyframeAnimations.degreeVec(-20.06F, -2.61F, -0.01F), CATMULLROM),
            new Keyframe(1.2F, KeyframeAnimations.degreeVec(-20F, -10F, 0F), CATMULLROM)))
        .addAnimation("right_arm", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(-145.31F, -37.48F, 117.67F), CATMULLROM),
            new Keyframe(0.1F, KeyframeAnimations.degreeVec(-127.43F, 5.1F, 98.71F), CATMULLROM),
            new Keyframe(0.2F, KeyframeAnimations.degreeVec(-102.07F, 56.78F, 134.03F), CATMULLROM),
            new Keyframe(0.3F, KeyframeAnimations.degreeVec(-97.36F, 47.41F, 128.59F), CATMULLROM),
            new Keyframe(0.4F, KeyframeAnimations.degreeVec(-91.67F, 46.16F, 127.96F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(-84.19F, 43.71F, 126.82F), CATMULLROM),
            new Keyframe(0.6F, KeyframeAnimations.degreeVec(-75.31F, 39.5F, 125.07F), CATMULLROM),
            new Keyframe(0.7F, KeyframeAnimations.degreeVec(-96.33F, 10.64F, 74.84F), CATMULLROM),
            new Keyframe(0.8F, KeyframeAnimations.degreeVec(-33.1F, 27.89F, 121.16F), CATMULLROM),
            new Keyframe(0.9F, KeyframeAnimations.degreeVec(-33.09F, -11.78F, 108.75F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.degreeVec(-109.41F, -51.05F, 149.89F), CATMULLROM),
            new Keyframe(1.1F, KeyframeAnimations.degreeVec(-130.64F, -29.18F, 107.43F), CATMULLROM),
            new Keyframe(1.2F, KeyframeAnimations.degreeVec(-131.93F, -29.64F, 107.93F), CATMULLROM)))
        .addAnimation("left_arm", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(-39.47F, 9.09F, 0F), CATMULLROM),
            new Keyframe(0.1F, KeyframeAnimations.degreeVec(-54.53F, -6.36F, -4.1F), CATMULLROM),
            new Keyframe(0.2F, KeyframeAnimations.degreeVec(-50.26F, -26.95F, -39.11F), CATMULLROM),
            new Keyframe(0.3F, KeyframeAnimations.degreeVec(-37.97F, -53.55F, -92.54F), CATMULLROM),
            new Keyframe(0.4F, KeyframeAnimations.degreeVec(-37.95F, -53.6F, -92.64F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(-37.96F, -53.57F, -92.58F), CATMULLROM),
            new Keyframe(0.6F, KeyframeAnimations.degreeVec(-37.98F, -53.53F, -92.5F), CATMULLROM),
            new Keyframe(0.7F, KeyframeAnimations.degreeVec(-37.98F, -53.53F, -92.5F), CATMULLROM),
            new Keyframe(0.8F, KeyframeAnimations.degreeVec(-34.66F, -53.54F, -94.17F), CATMULLROM),
            new Keyframe(0.9F, KeyframeAnimations.degreeVec(-38.2F, -44.36F, -78.95F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.degreeVec(-39.41F, 6.71F, -3.52F), CATMULLROM),
            new Keyframe(1.1F, KeyframeAnimations.degreeVec(-39.47F, 9.09F, 0F), CATMULLROM),
            new Keyframe(1.2F, KeyframeAnimations.degreeVec(-39.47F, 9.09F, 0F), CATMULLROM)))
        .addAnimation("right_leg", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(-39.65F, 1.96F, 4.44F), CATMULLROM),
            new Keyframe(0.1F, KeyframeAnimations.degreeVec(-45.65F, 1.55F, 4.97F), CATMULLROM),
            new Keyframe(0.2F, KeyframeAnimations.degreeVec(-36.6F, -9.1F, 4.19F), CATMULLROM),
            new Keyframe(0.3F, KeyframeAnimations.degreeVec(-37.04F, -37.7F, 8.77F), CATMULLROM),
            new Keyframe(0.4F, KeyframeAnimations.degreeVec(-37.04F, -37.7F, 8.77F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(-37.04F, -37.7F, 8.77F), CATMULLROM),
            new Keyframe(0.6F, KeyframeAnimations.degreeVec(-37.04F, -37.7F, 8.77F), CATMULLROM),
            new Keyframe(0.7F, KeyframeAnimations.degreeVec(-37.04F, -37.7F, 8.77F), CATMULLROM),
            new Keyframe(0.8F, KeyframeAnimations.degreeVec(-37.05F, -37.72F, 8.77F), CATMULLROM),
            new Keyframe(0.9F, KeyframeAnimations.degreeVec(-36.07F, -34.61F, 7.79F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.degreeVec(-41.67F, -9.69F, 4.7F), CATMULLROM),
            new Keyframe(1.1F, KeyframeAnimations.degreeVec(-39.65F, 1.96F, 4.44F), CATMULLROM),
            new Keyframe(1.2F, KeyframeAnimations.degreeVec(-39.65F, 1.96F, 4.44F), CATMULLROM)))
        .addAnimation("left_leg", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(-52.09F, -13.97F, -0.56F), CATMULLROM),
            new Keyframe(0.1F, KeyframeAnimations.degreeVec(-65.02F, -14.38F, 1.36F), CATMULLROM),
            new Keyframe(0.2F, KeyframeAnimations.degreeVec(-63.47F, -24.93F, 6.39F), CATMULLROM),
            new Keyframe(0.3F, KeyframeAnimations.degreeVec(-44.53F, -53.97F, 0.48F), CATMULLROM),
            new Keyframe(0.4F, KeyframeAnimations.degreeVec(-44.53F, -53.97F, 0.48F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(-44.53F, -53.97F, 0.48F), CATMULLROM),
            new Keyframe(0.6F, KeyframeAnimations.degreeVec(-44.53F, -53.97F, 0.48F), CATMULLROM),
            new Keyframe(0.7F, KeyframeAnimations.degreeVec(-44.53F, -53.97F, 0.48F), CATMULLROM),
            new Keyframe(0.8F, KeyframeAnimations.degreeVec(-44.51F, -53.99F, 0.47F), CATMULLROM),
            new Keyframe(0.9F, KeyframeAnimations.degreeVec(-50.13F, -50.78F, 1.64F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.degreeVec(-59.47F, -25.79F, 2.32F), CATMULLROM),
            new Keyframe(1.1F, KeyframeAnimations.degreeVec(-52.09F, -13.97F, -0.56F), CATMULLROM),
            new Keyframe(1.2F, KeyframeAnimations.degreeVec(-52.09F, -13.97F, -0.56F), CATMULLROM)))
        .build();

    /** Hunter v2: kneel at the kill, lift it onto the shoulders (contact 0.55 = tick 11); 1.40 s = 28 ticks. */
    public static final AnimationDefinition HUNTER_TAKE_KILL = AnimationDefinition.Builder
        .withLength(1.4F)
        .addAnimation("root", new AnimationChannel(POSITION,
            new Keyframe(0F, KeyframeAnimations.posVec(0F, -0.6F, 0.4F), CATMULLROM),
            new Keyframe(0.1F, KeyframeAnimations.posVec(0F, -2.01F, 0.55F), CATMULLROM),
            new Keyframe(0.2F, KeyframeAnimations.posVec(0F, -4.79F, 0.85F), CATMULLROM),
            new Keyframe(0.3F, KeyframeAnimations.posVec(0F, -6.2F, 1F), CATMULLROM),
            new Keyframe(0.4F, KeyframeAnimations.posVec(0F, -6.2F, 1F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.posVec(0F, -6.2F, 1F), CATMULLROM),
            new Keyframe(0.6F, KeyframeAnimations.posVec(0F, -5.78F, 0.93F), CATMULLROM),
            new Keyframe(0.7F, KeyframeAnimations.posVec(0F, -3.48F, 0.56F), CATMULLROM),
            new Keyframe(0.8F, KeyframeAnimations.posVec(0F, -2.45F, 0.4F), CATMULLROM),
            new Keyframe(0.9F, KeyframeAnimations.posVec(0F, -1.53F, 0.4F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.posVec(0F, -0.64F, 0.4F), CATMULLROM),
            new Keyframe(1.1F, KeyframeAnimations.posVec(0F, -0.6F, 0.4F), CATMULLROM),
            new Keyframe(1.2F, KeyframeAnimations.posVec(0F, -0.6F, 0.4F), CATMULLROM),
            new Keyframe(1.3F, KeyframeAnimations.posVec(0F, -0.6F, 0.4F), CATMULLROM),
            new Keyframe(1.4F, KeyframeAnimations.posVec(0F, -0.6F, 0.4F), CATMULLROM)))
        .addAnimation("torso", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(10F, 0F, 0F), CATMULLROM),
            new Keyframe(0.1F, KeyframeAnimations.degreeVec(14.93F, 0F, 0F), CATMULLROM),
            new Keyframe(0.2F, KeyframeAnimations.degreeVec(25.12F, 0F, 0F), CATMULLROM),
            new Keyframe(0.3F, KeyframeAnimations.degreeVec(30F, 0F, 0F), CATMULLROM),
            new Keyframe(0.4F, KeyframeAnimations.degreeVec(31.09F, 0F, 0F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(31.97F, 0F, 0F), CATMULLROM),
            new Keyframe(0.6F, KeyframeAnimations.degreeVec(29.76F, 0F, 0F), CATMULLROM),
            new Keyframe(0.7F, KeyframeAnimations.degreeVec(17.44F, 0F, 0F), CATMULLROM),
            new Keyframe(0.8F, KeyframeAnimations.degreeVec(11.89F, 0F, 0F), CATMULLROM),
            new Keyframe(0.9F, KeyframeAnimations.degreeVec(10.83F, 0F, 0F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.degreeVec(10.04F, 0F, 0F), CATMULLROM),
            new Keyframe(1.1F, KeyframeAnimations.degreeVec(10F, 0F, 0F), CATMULLROM),
            new Keyframe(1.2F, KeyframeAnimations.degreeVec(10F, 0F, 0F), CATMULLROM),
            new Keyframe(1.3F, KeyframeAnimations.degreeVec(10F, 0F, 0F), CATMULLROM),
            new Keyframe(1.4F, KeyframeAnimations.degreeVec(10F, 0F, 0F), CATMULLROM)))
        .addAnimation("head", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(4F, 0F, 0F), CATMULLROM),
            new Keyframe(0.1F, KeyframeAnimations.degreeVec(7.48F, 0F, 0F), CATMULLROM),
            new Keyframe(0.2F, KeyframeAnimations.degreeVec(14.58F, 0F, 0F), CATMULLROM),
            new Keyframe(0.3F, KeyframeAnimations.degreeVec(18F, 0F, 0F), CATMULLROM),
            new Keyframe(0.4F, KeyframeAnimations.degreeVec(22.99F, 0F, 0F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(20.88F, 0F, 0F), CATMULLROM),
            new Keyframe(0.6F, KeyframeAnimations.degreeVec(13.9F, 0F, 0F), CATMULLROM),
            new Keyframe(0.7F, KeyframeAnimations.degreeVec(1.6F, 0F, 0F), CATMULLROM),
            new Keyframe(0.8F, KeyframeAnimations.degreeVec(-5.99F, 0F, 0F), CATMULLROM),
            new Keyframe(0.9F, KeyframeAnimations.degreeVec(0.86F, 0F, 0F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.degreeVec(9.67F, 0F, 0F), CATMULLROM),
            new Keyframe(1.1F, KeyframeAnimations.degreeVec(9.17F, 0F, 0F), CATMULLROM),
            new Keyframe(1.2F, KeyframeAnimations.degreeVec(8.1F, 0F, 0F), CATMULLROM),
            new Keyframe(1.3F, KeyframeAnimations.degreeVec(8.01F, 0F, 0F), CATMULLROM),
            new Keyframe(1.4F, KeyframeAnimations.degreeVec(8F, 0F, 0F), CATMULLROM)))
        .addAnimation("right_arm", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(1.59F, -60.79F, 26.57F), CATMULLROM),
            new Keyframe(0.1F, KeyframeAnimations.degreeVec(-28.47F, -53.16F, 42.09F), CATMULLROM),
            new Keyframe(0.2F, KeyframeAnimations.degreeVec(-84.72F, -38.15F, 57.54F), CATMULLROM),
            new Keyframe(0.3F, KeyframeAnimations.degreeVec(-95.96F, -30.57F, 62.62F), CATMULLROM),
            new Keyframe(0.4F, KeyframeAnimations.degreeVec(-97.07F, -31.16F, 62.26F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(-88.21F, -33.18F, 60.99F), CATMULLROM),
            new Keyframe(0.6F, KeyframeAnimations.degreeVec(-84.11F, -33.27F, 60.93F), CATMULLROM),
            new Keyframe(0.7F, KeyframeAnimations.degreeVec(-88.54F, -30.98F, 62.38F), CATMULLROM),
            new Keyframe(0.8F, KeyframeAnimations.degreeVec(-56.57F, -22F, 87.66F), CATMULLROM),
            new Keyframe(0.9F, KeyframeAnimations.degreeVec(12.36F, 67.38F, 167.31F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.degreeVec(37.78F, 64.27F, 160.97F), CATMULLROM),
            new Keyframe(1.1F, KeyframeAnimations.degreeVec(33.78F, 57.97F, 152.75F), CATMULLROM),
            new Keyframe(1.2F, KeyframeAnimations.degreeVec(33.78F, 57.97F, 152.75F), CATMULLROM),
            new Keyframe(1.3F, KeyframeAnimations.degreeVec(33.78F, 57.97F, 152.75F), CATMULLROM),
            new Keyframe(1.4F, KeyframeAnimations.degreeVec(33.78F, 57.97F, 152.75F), CATMULLROM)))
        .addAnimation("left_arm", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(1.59F, 60.79F, -26.57F), CATMULLROM),
            new Keyframe(0.1F, KeyframeAnimations.degreeVec(-11.24F, 59.57F, -29.85F), CATMULLROM),
            new Keyframe(0.2F, KeyframeAnimations.degreeVec(-38.45F, 57.43F, -34.68F), CATMULLROM),
            new Keyframe(0.3F, KeyframeAnimations.degreeVec(-41.72F, 56.31F, -36.87F), CATMULLROM),
            new Keyframe(0.4F, KeyframeAnimations.degreeVec(-41.63F, 56.34F, -36.82F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(-70.15F, 42.87F, -53.72F), CATMULLROM),
            new Keyframe(0.6F, KeyframeAnimations.degreeVec(-84.21F, 33.22F, -60.96F), CATMULLROM),
            new Keyframe(0.7F, KeyframeAnimations.degreeVec(-88.54F, 30.98F, -62.38F), CATMULLROM),
            new Keyframe(0.8F, KeyframeAnimations.degreeVec(-56.48F, 22F, -87.66F), CATMULLROM),
            new Keyframe(0.9F, KeyframeAnimations.degreeVec(12.38F, -67.37F, -167.28F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.degreeVec(37.78F, -64.27F, -160.97F), CATMULLROM),
            new Keyframe(1.1F, KeyframeAnimations.degreeVec(33.78F, -57.97F, -152.75F), CATMULLROM),
            new Keyframe(1.2F, KeyframeAnimations.degreeVec(33.78F, -57.97F, -152.75F), CATMULLROM),
            new Keyframe(1.3F, KeyframeAnimations.degreeVec(33.78F, -57.97F, -152.75F), CATMULLROM),
            new Keyframe(1.4F, KeyframeAnimations.degreeVec(33.78F, -57.97F, -152.75F), CATMULLROM)))
        .addAnimation("right_leg", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(-17.64F, 7.95F, 4.04F), CATMULLROM),
            new Keyframe(0.1F, KeyframeAnimations.degreeVec(-39.34F, 7.94F, 5.25F), CATMULLROM),
            new Keyframe(0.2F, KeyframeAnimations.degreeVec(-25.79F, 7.82F, 11.28F), CATMULLROM),
            new Keyframe(0.3F, KeyframeAnimations.degreeVec(-5.96F, 7.69F, 15.24F), CATMULLROM),
            new Keyframe(0.4F, KeyframeAnimations.degreeVec(-5.92F, 7.69F, 15.27F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(-5.95F, 7.69F, 15.27F), CATMULLROM),
            new Keyframe(0.6F, KeyframeAnimations.degreeVec(-6.51F, 7.74F, 13.95F), CATMULLROM),
            new Keyframe(0.7F, KeyframeAnimations.degreeVec(-4.09F, 7.86F, 9.71F), CATMULLROM),
            new Keyframe(0.8F, KeyframeAnimations.degreeVec(-0.01F, 7.88F, 8.42F), CATMULLROM),
            new Keyframe(0.9F, KeyframeAnimations.degreeVec(-13.04F, 7.9F, 7.5F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.degreeVec(-19.38F, 7.95F, 4.1F), CATMULLROM),
            new Keyframe(1.1F, KeyframeAnimations.degreeVec(-17.64F, 7.95F, 4.04F), CATMULLROM),
            new Keyframe(1.2F, KeyframeAnimations.degreeVec(-17.64F, 7.95F, 4.04F), CATMULLROM),
            new Keyframe(1.3F, KeyframeAnimations.degreeVec(-17.64F, 7.95F, 4.04F), CATMULLROM),
            new Keyframe(1.4F, KeyframeAnimations.degreeVec(-17.64F, 7.95F, 4.04F), CATMULLROM)))
        .addAnimation("left_leg", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(-27.01F, -7.97F, -0.47F), CATMULLROM),
            new Keyframe(0.1F, KeyframeAnimations.degreeVec(-49.86F, -7.97F, -0.43F), CATMULLROM),
            new Keyframe(0.2F, KeyframeAnimations.degreeVec(-86.67F, -7.97F, 0.48F), CATMULLROM),
            new Keyframe(0.3F, KeyframeAnimations.degreeVec(-93.27F, -7.97F, 1.3F), CATMULLROM),
            new Keyframe(0.4F, KeyframeAnimations.degreeVec(-93.29F, -7.97F, 1.3F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(-93.29F, -7.97F, 1.3F), CATMULLROM),
            new Keyframe(0.6F, KeyframeAnimations.degreeVec(-89.25F, -7.97F, 1.13F), CATMULLROM),
            new Keyframe(0.7F, KeyframeAnimations.degreeVec(-66.22F, -7.97F, 0.46F), CATMULLROM),
            new Keyframe(0.8F, KeyframeAnimations.degreeVec(-54.06F, -7.97F, 0.27F), CATMULLROM),
            new Keyframe(0.9F, KeyframeAnimations.degreeVec(-53.96F, -7.97F, 0.01F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.degreeVec(-27.77F, -7.97F, -0.47F), CATMULLROM),
            new Keyframe(1.1F, KeyframeAnimations.degreeVec(-27.01F, -7.97F, -0.47F), CATMULLROM),
            new Keyframe(1.2F, KeyframeAnimations.degreeVec(-27F, -7.97F, -0.47F), CATMULLROM),
            new Keyframe(1.3F, KeyframeAnimations.degreeVec(-27.01F, -7.97F, -0.47F), CATMULLROM),
            new Keyframe(1.4F, KeyframeAnimations.degreeVec(-27.01F, -7.97F, -0.47F), CATMULLROM)))
        .build();

    /** Hunter v2: the kill across the shoulders, hands on its legs (locomotion; WALK_LADEN's stride), 1.20 s loop. */
    public static final AnimationDefinition HUNTER_HAUL = AnimationDefinition.Builder
        .withLength(1.2F).looping()
        .addAnimation("root", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(0F, -2F, 0F), CATMULLROM),
            new Keyframe(0.24F, KeyframeAnimations.degreeVec(0F, -0.49F, 0F), CATMULLROM),
            new Keyframe(0.48F, KeyframeAnimations.degreeVec(0F, 1.64F, 0F), CATMULLROM),
            new Keyframe(0.72F, KeyframeAnimations.degreeVec(0F, 1.5F, 0F), CATMULLROM),
            new Keyframe(0.96F, KeyframeAnimations.degreeVec(0F, -0.72F, 0F), CATMULLROM),
            new Keyframe(1.2F, KeyframeAnimations.degreeVec(0F, -2F, 0F), CATMULLROM)))
        .addAnimation("root", new AnimationChannel(POSITION,
            new Keyframe(0F, KeyframeAnimations.posVec(0F, -3.35F, 0.4F), CATMULLROM),
            new Keyframe(0.24F, KeyframeAnimations.posVec(0F, -2.87F, 0.4F), CATMULLROM),
            new Keyframe(0.48F, KeyframeAnimations.posVec(0F, -2.83F, 0.4F), CATMULLROM),
            new Keyframe(0.72F, KeyframeAnimations.posVec(0F, -3.51F, 0.4F), CATMULLROM),
            new Keyframe(0.96F, KeyframeAnimations.posVec(0F, -2.56F, 0.4F), CATMULLROM),
            new Keyframe(1.2F, KeyframeAnimations.posVec(0F, -3.35F, 0.4F), CATMULLROM)))
        .addAnimation("torso", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(15.2F, 0F, 0F), CATMULLROM),
            new Keyframe(0.24F, KeyframeAnimations.degreeVec(13F, 0F, -1.48F), CATMULLROM),
            new Keyframe(0.48F, KeyframeAnimations.degreeVec(14.29F, 0F, -0.91F), CATMULLROM),
            new Keyframe(0.72F, KeyframeAnimations.degreeVec(14.39F, 0F, 0.96F), CATMULLROM),
            new Keyframe(0.96F, KeyframeAnimations.degreeVec(13F, 0F, 1.48F), CATMULLROM),
            new Keyframe(1.2F, KeyframeAnimations.degreeVec(15.2F, 0F, 0F), CATMULLROM)))
        .addAnimation("head", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(8F, 0F, 0F), CATMULLROM),
            new Keyframe(0.24F, KeyframeAnimations.degreeVec(8F, 0F, 1.11F), CATMULLROM),
            new Keyframe(0.48F, KeyframeAnimations.degreeVec(8F, 0F, 0.68F), CATMULLROM),
            new Keyframe(0.72F, KeyframeAnimations.degreeVec(8F, 0F, -0.69F), CATMULLROM),
            new Keyframe(0.96F, KeyframeAnimations.degreeVec(8F, 0F, -1.13F), CATMULLROM),
            new Keyframe(1.2F, KeyframeAnimations.degreeVec(8F, 0F, 0F), CATMULLROM)))
        .addAnimation("right_arm", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(34.05F, 58.62F, 153.43F), CATMULLROM),
            new Keyframe(0.24F, KeyframeAnimations.degreeVec(33.05F, 56.77F, 151.54F), CATMULLROM),
            new Keyframe(0.48F, KeyframeAnimations.degreeVec(34.17F, 59.05F, 153.89F), CATMULLROM),
            new Keyframe(0.72F, KeyframeAnimations.degreeVec(33.23F, 57.19F, 151.98F), CATMULLROM),
            new Keyframe(0.96F, KeyframeAnimations.degreeVec(33.76F, 58.02F, 152.8F), CATMULLROM),
            new Keyframe(1.2F, KeyframeAnimations.degreeVec(34.05F, 58.62F, 153.43F), CATMULLROM)))
        .addAnimation("left_arm", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(34.05F, -58.62F, -153.43F), CATMULLROM),
            new Keyframe(0.24F, KeyframeAnimations.degreeVec(33.05F, -56.77F, -151.54F), CATMULLROM),
            new Keyframe(0.48F, KeyframeAnimations.degreeVec(34.17F, -59.05F, -153.89F), CATMULLROM),
            new Keyframe(0.72F, KeyframeAnimations.degreeVec(33.23F, -57.19F, -151.98F), CATMULLROM),
            new Keyframe(0.96F, KeyframeAnimations.degreeVec(33.76F, -58.02F, -152.8F), CATMULLROM),
            new Keyframe(1.2F, KeyframeAnimations.degreeVec(34.05F, -58.62F, -153.43F), CATMULLROM)))
        .addAnimation("right_leg", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(-65.46F, 9.96F, -2.52F), CATMULLROM),
            new Keyframe(0.24F, KeyframeAnimations.degreeVec(-56.04F, 8.46F, 0.09F), CATMULLROM),
            new Keyframe(0.48F, KeyframeAnimations.degreeVec(-41.41F, 6.4F, 2.71F), CATMULLROM),
            new Keyframe(0.72F, KeyframeAnimations.degreeVec(-21.86F, 6.37F, 6.08F), CATMULLROM),
            new Keyframe(0.96F, KeyframeAnimations.degreeVec(-51.07F, 8.57F, 2.86F), CATMULLROM),
            new Keyframe(1.2F, KeyframeAnimations.degreeVec(-65.46F, 9.96F, -2.52F), CATMULLROM)))
        .addAnimation("left_leg", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(-33.85F, -5.95F, -4.38F), CATMULLROM),
            new Keyframe(0.24F, KeyframeAnimations.degreeVec(-23.83F, -7.45F, -6.41F), CATMULLROM),
            new Keyframe(0.48F, KeyframeAnimations.degreeVec(-68.13F, -9.54F, 1.04F), CATMULLROM),
            new Keyframe(0.72F, KeyframeAnimations.degreeVec(-66.03F, -9.54F, 1.26F), CATMULLROM),
            new Keyframe(0.96F, KeyframeAnimations.degreeVec(-47.61F, -7.37F, -1.31F), CATMULLROM),
            new Keyframe(1.2F, KeyframeAnimations.degreeVec(-33.85F, -5.95F, -4.38F), CATMULLROM)))
        .build();

    /** Hunter v2: kneeling skinning at the kill on the floor, HIDE_SCRAPE tick 4; 1.20 s loop = 24 ticks. */
    public static final AnimationDefinition HUNTER_SKIN_KNEEL = AnimationDefinition.Builder
        .withLength(1.2F).looping()
        .addAnimation("root", new AnimationChannel(POSITION,
            new Keyframe(0F, KeyframeAnimations.posVec(0F, -6.2F, 1F), CATMULLROM),
            new Keyframe(0.24F, KeyframeAnimations.posVec(0F, -6.2F, 1F), CATMULLROM),
            new Keyframe(0.48F, KeyframeAnimations.posVec(0F, -6.2F, 1F), CATMULLROM),
            new Keyframe(0.72F, KeyframeAnimations.posVec(0F, -6.2F, 1F), CATMULLROM),
            new Keyframe(0.96F, KeyframeAnimations.posVec(0F, -6.2F, 1F), CATMULLROM),
            new Keyframe(1.2F, KeyframeAnimations.posVec(0F, -6.2F, 1F), CATMULLROM)))
        .addAnimation("torso", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(30F, 0F, 0F), CATMULLROM),
            new Keyframe(0.24F, KeyframeAnimations.degreeVec(32.31F, -4.48F, 0F), CATMULLROM),
            new Keyframe(0.48F, KeyframeAnimations.degreeVec(32.18F, 1F, 0F), CATMULLROM),
            new Keyframe(0.72F, KeyframeAnimations.degreeVec(29.28F, 3.69F, 0F), CATMULLROM),
            new Keyframe(0.96F, KeyframeAnimations.degreeVec(29.54F, 1.47F, 0F), CATMULLROM),
            new Keyframe(1.2F, KeyframeAnimations.degreeVec(30F, 0F, 0F), CATMULLROM)))
        .addAnimation("head", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(8F, 0F, 0F), CATMULLROM),
            new Keyframe(0.24F, KeyframeAnimations.degreeVec(11.59F, 0F, 0F), CATMULLROM),
            new Keyframe(0.48F, KeyframeAnimations.degreeVec(9.15F, 0F, 0F), CATMULLROM),
            new Keyframe(0.72F, KeyframeAnimations.degreeVec(4.26F, -0.03F, 0F), CATMULLROM),
            new Keyframe(0.96F, KeyframeAnimations.degreeVec(2.02F, -13.83F, 0F), CATMULLROM),
            new Keyframe(1.2F, KeyframeAnimations.degreeVec(8F, 0F, 0F), CATMULLROM)))
        .addAnimation("right_arm", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(-102.91F, -19.81F, 68.48F), CATMULLROM),
            new Keyframe(0.24F, KeyframeAnimations.degreeVec(-96.86F, -22.52F, 67.11F), CATMULLROM),
            new Keyframe(0.48F, KeyframeAnimations.degreeVec(-96.51F, -35.47F, 59.46F), CATMULLROM),
            new Keyframe(0.72F, KeyframeAnimations.degreeVec(-101.21F, -34.65F, 60.03F), CATMULLROM),
            new Keyframe(0.96F, KeyframeAnimations.degreeVec(-103.48F, -24.38F, 66.13F), CATMULLROM),
            new Keyframe(1.2F, KeyframeAnimations.degreeVec(-102.91F, -19.81F, 68.48F), CATMULLROM)))
        .addAnimation("left_arm", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(-89.78F, 29.11F, -63.49F), CATMULLROM),
            new Keyframe(0.24F, KeyframeAnimations.degreeVec(-94.04F, 29.22F, -63.43F), CATMULLROM),
            new Keyframe(0.48F, KeyframeAnimations.degreeVec(-88.48F, 30.5F, -62.67F), CATMULLROM),
            new Keyframe(0.72F, KeyframeAnimations.degreeVec(-85.29F, 30.86F, -62.45F), CATMULLROM),
            new Keyframe(0.96F, KeyframeAnimations.degreeVec(-87.9F, 29.91F, -63.02F), CATMULLROM),
            new Keyframe(1.2F, KeyframeAnimations.degreeVec(-89.78F, 29.12F, -63.49F), CATMULLROM)))
        .addAnimation("right_leg", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(-5.96F, 7.69F, 15.24F), CATMULLROM),
            new Keyframe(0.24F, KeyframeAnimations.degreeVec(-5.96F, 7.69F, 15.24F), CATMULLROM),
            new Keyframe(0.48F, KeyframeAnimations.degreeVec(-5.96F, 7.69F, 15.24F), CATMULLROM),
            new Keyframe(0.72F, KeyframeAnimations.degreeVec(-5.96F, 7.69F, 15.24F), CATMULLROM),
            new Keyframe(0.96F, KeyframeAnimations.degreeVec(-5.96F, 7.69F, 15.24F), CATMULLROM),
            new Keyframe(1.2F, KeyframeAnimations.degreeVec(-5.96F, 7.69F, 15.24F), CATMULLROM)))
        .addAnimation("left_leg", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(-93.27F, -7.97F, 1.3F), CATMULLROM),
            new Keyframe(0.24F, KeyframeAnimations.degreeVec(-93.27F, -7.97F, 1.3F), CATMULLROM),
            new Keyframe(0.48F, KeyframeAnimations.degreeVec(-93.27F, -7.97F, 1.3F), CATMULLROM),
            new Keyframe(0.72F, KeyframeAnimations.degreeVec(-93.27F, -7.97F, 1.3F), CATMULLROM),
            new Keyframe(0.96F, KeyframeAnimations.degreeVec(-93.27F, -7.97F, 1.3F), CATMULLROM),
            new Keyframe(1.2F, KeyframeAnimations.degreeVec(-93.27F, -7.97F, 1.3F), CATMULLROM)))
        .build();

    /** Hunter v2: kneeling butchering, CLEAVER_CHOP tick 9; 0.85 s loop = 17 ticks. */
    public static final AnimationDefinition HUNTER_BUTCHER_KNEEL = AnimationDefinition.Builder
        .withLength(0.85F).looping()
        .addAnimation("root", new AnimationChannel(POSITION,
            new Keyframe(0F, KeyframeAnimations.posVec(0F, -6.2F, 1F), CATMULLROM),
            new Keyframe(0.28F, KeyframeAnimations.posVec(0F, -6.2F, 1F), CATMULLROM),
            new Keyframe(0.57F, KeyframeAnimations.posVec(0F, -6.2F, 1F), CATMULLROM),
            new Keyframe(0.85F, KeyframeAnimations.posVec(0F, -6.2F, 1F), CATMULLROM)))
        .addAnimation("torso", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(30F, 0F, 0F), CATMULLROM),
            new Keyframe(0.28F, KeyframeAnimations.degreeVec(24.17F, 7.77F, 0F), CATMULLROM),
            new Keyframe(0.57F, KeyframeAnimations.degreeVec(33.21F, -3.05F, 0F), CATMULLROM),
            new Keyframe(0.85F, KeyframeAnimations.degreeVec(30F, 0F, 0F), CATMULLROM)))
        .addAnimation("head", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(10F, 0F, 0F), CATMULLROM),
            new Keyframe(0.28F, KeyframeAnimations.degreeVec(6.13F, 0F, 0F), CATMULLROM),
            new Keyframe(0.57F, KeyframeAnimations.degreeVec(11.62F, 0F, 0F), CATMULLROM),
            new Keyframe(0.85F, KeyframeAnimations.degreeVec(10F, 0F, 0F), CATMULLROM)))
        .addAnimation("right_arm", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(-100.37F, -27.36F, 64.5F), CATMULLROM),
            new Keyframe(0.28F, KeyframeAnimations.degreeVec(-73.58F, -1.67F, 76.75F), CATMULLROM),
            new Keyframe(0.57F, KeyframeAnimations.degreeVec(-94.24F, -28.65F, 63.76F), CATMULLROM),
            new Keyframe(0.85F, KeyframeAnimations.degreeVec(-100.37F, -27.36F, 64.5F), CATMULLROM)))
        .addAnimation("left_arm", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(-88.33F, 30.15F, -62.87F), CATMULLROM),
            new Keyframe(0.28F, KeyframeAnimations.degreeVec(-79.01F, 32.21F, -61.61F), CATMULLROM),
            new Keyframe(0.57F, KeyframeAnimations.degreeVec(-91.83F, 29.58F, -63.21F), CATMULLROM),
            new Keyframe(0.85F, KeyframeAnimations.degreeVec(-88.33F, 30.15F, -62.87F), CATMULLROM)))
        .addAnimation("right_leg", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(-5.96F, 7.69F, 15.24F), CATMULLROM),
            new Keyframe(0.28F, KeyframeAnimations.degreeVec(-5.96F, 7.69F, 15.24F), CATMULLROM),
            new Keyframe(0.57F, KeyframeAnimations.degreeVec(-5.96F, 7.69F, 15.24F), CATMULLROM),
            new Keyframe(0.85F, KeyframeAnimations.degreeVec(-5.96F, 7.69F, 15.24F), CATMULLROM)))
        .addAnimation("left_leg", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(-93.27F, -7.97F, 1.3F), CATMULLROM),
            new Keyframe(0.28F, KeyframeAnimations.degreeVec(-93.27F, -7.97F, 1.3F), CATMULLROM),
            new Keyframe(0.57F, KeyframeAnimations.degreeVec(-93.27F, -7.97F, 1.3F), CATMULLROM),
            new Keyframe(0.85F, KeyframeAnimations.degreeVec(-93.27F, -7.97F, 1.3F), CATMULLROM)))
        .build();

    /** Hunter v2: idle at the lodge (checks the bow; variants squat and stretch), 5.00 s loop. */
    public static final AnimationDefinition IDLE_HUNTER = AnimationDefinition.Builder
        .withLength(5F).looping()
        .addAnimation("root", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 3F, 0F), CATMULLROM),
            new Keyframe(0.25F, KeyframeAnimations.degreeVec(0F, 3F, 0F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(0F, 3F, 0F), CATMULLROM),
            new Keyframe(0.75F, KeyframeAnimations.degreeVec(0F, 3F, 0F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.degreeVec(0F, 3F, 0F), CATMULLROM),
            new Keyframe(1.25F, KeyframeAnimations.degreeVec(0F, 3F, 0F), CATMULLROM),
            new Keyframe(1.5F, KeyframeAnimations.degreeVec(0F, 3F, 0F), CATMULLROM),
            new Keyframe(1.75F, KeyframeAnimations.degreeVec(0F, 3F, 0F), CATMULLROM),
            new Keyframe(2F, KeyframeAnimations.degreeVec(0F, 3F, 0F), CATMULLROM),
            new Keyframe(2.25F, KeyframeAnimations.degreeVec(0F, 3F, 0F), CATMULLROM),
            new Keyframe(2.5F, KeyframeAnimations.degreeVec(0F, 3F, 0F), CATMULLROM),
            new Keyframe(2.75F, KeyframeAnimations.degreeVec(0F, 3F, 0F), CATMULLROM),
            new Keyframe(3F, KeyframeAnimations.degreeVec(0F, 3F, 0F), CATMULLROM),
            new Keyframe(3.25F, KeyframeAnimations.degreeVec(0F, 3F, 0F), CATMULLROM),
            new Keyframe(3.5F, KeyframeAnimations.degreeVec(0F, 3F, 0F), CATMULLROM),
            new Keyframe(3.75F, KeyframeAnimations.degreeVec(0F, 3F, 0F), CATMULLROM),
            new Keyframe(4F, KeyframeAnimations.degreeVec(0F, 3F, 0F), CATMULLROM),
            new Keyframe(4.25F, KeyframeAnimations.degreeVec(0F, 3F, 0F), CATMULLROM),
            new Keyframe(4.5F, KeyframeAnimations.degreeVec(0F, 3F, 0F), CATMULLROM),
            new Keyframe(4.75F, KeyframeAnimations.degreeVec(0F, 3F, 0F), CATMULLROM),
            new Keyframe(5F, KeyframeAnimations.degreeVec(0F, 3F, 0F), CATMULLROM)))
        .addAnimation("root", new AnimationChannel(POSITION,
            new Keyframe(0F, KeyframeAnimations.posVec(0F, -0.3F, 0F), CATMULLROM),
            new Keyframe(0.25F, KeyframeAnimations.posVec(0F, -0.3F, 0F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.posVec(0F, -0.3F, 0F), CATMULLROM),
            new Keyframe(0.75F, KeyframeAnimations.posVec(0F, -0.3F, 0F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.posVec(0F, -0.3F, 0F), CATMULLROM),
            new Keyframe(1.25F, KeyframeAnimations.posVec(0F, -0.3F, 0F), CATMULLROM),
            new Keyframe(1.5F, KeyframeAnimations.posVec(0F, -0.3F, 0F), CATMULLROM),
            new Keyframe(1.75F, KeyframeAnimations.posVec(0F, -0.3F, 0F), CATMULLROM),
            new Keyframe(2F, KeyframeAnimations.posVec(0F, -0.3F, 0F), CATMULLROM),
            new Keyframe(2.25F, KeyframeAnimations.posVec(0F, -0.3F, 0F), CATMULLROM),
            new Keyframe(2.5F, KeyframeAnimations.posVec(0F, -0.3F, 0F), CATMULLROM),
            new Keyframe(2.75F, KeyframeAnimations.posVec(0F, -0.3F, 0F), CATMULLROM),
            new Keyframe(3F, KeyframeAnimations.posVec(0F, -0.3F, 0F), CATMULLROM),
            new Keyframe(3.25F, KeyframeAnimations.posVec(0F, -0.3F, 0F), CATMULLROM),
            new Keyframe(3.5F, KeyframeAnimations.posVec(0F, -0.3F, 0F), CATMULLROM),
            new Keyframe(3.75F, KeyframeAnimations.posVec(0F, -0.3F, 0F), CATMULLROM),
            new Keyframe(4F, KeyframeAnimations.posVec(0F, -0.3F, 0F), CATMULLROM),
            new Keyframe(4.25F, KeyframeAnimations.posVec(0F, -0.3F, 0F), CATMULLROM),
            new Keyframe(4.5F, KeyframeAnimations.posVec(0F, -0.3F, 0F), CATMULLROM),
            new Keyframe(4.75F, KeyframeAnimations.posVec(0F, -0.3F, 0F), CATMULLROM),
            new Keyframe(5F, KeyframeAnimations.posVec(0F, -0.3F, 0F), CATMULLROM)))
        .addAnimation("torso", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(4F, 0F, 0F), CATMULLROM),
            new Keyframe(0.25F, KeyframeAnimations.degreeVec(4F, 0F, 0F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(4F, 0F, 0F), CATMULLROM),
            new Keyframe(0.75F, KeyframeAnimations.degreeVec(4F, 0F, 0F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.degreeVec(4F, 0F, 0F), CATMULLROM),
            new Keyframe(1.25F, KeyframeAnimations.degreeVec(4F, 0F, 0F), CATMULLROM),
            new Keyframe(1.5F, KeyframeAnimations.degreeVec(4F, 0F, 0F), CATMULLROM),
            new Keyframe(1.75F, KeyframeAnimations.degreeVec(4F, 0F, 0F), CATMULLROM),
            new Keyframe(2F, KeyframeAnimations.degreeVec(4F, 0F, 0F), CATMULLROM),
            new Keyframe(2.25F, KeyframeAnimations.degreeVec(4F, 0F, 0F), CATMULLROM),
            new Keyframe(2.5F, KeyframeAnimations.degreeVec(4F, 0F, 0F), CATMULLROM),
            new Keyframe(2.75F, KeyframeAnimations.degreeVec(4F, 0F, 0F), CATMULLROM),
            new Keyframe(3F, KeyframeAnimations.degreeVec(4F, 0F, 0F), CATMULLROM),
            new Keyframe(3.25F, KeyframeAnimations.degreeVec(4F, 0F, 0F), CATMULLROM),
            new Keyframe(3.5F, KeyframeAnimations.degreeVec(4F, 0F, 0F), CATMULLROM),
            new Keyframe(3.75F, KeyframeAnimations.degreeVec(4F, 0F, 0F), CATMULLROM),
            new Keyframe(4F, KeyframeAnimations.degreeVec(4F, 0F, 0F), CATMULLROM),
            new Keyframe(4.25F, KeyframeAnimations.degreeVec(4F, 0F, 0F), CATMULLROM),
            new Keyframe(4.5F, KeyframeAnimations.degreeVec(4F, 0F, 0F), CATMULLROM),
            new Keyframe(4.75F, KeyframeAnimations.degreeVec(4F, 0F, 0F), CATMULLROM),
            new Keyframe(5F, KeyframeAnimations.degreeVec(4F, 0F, 0F), CATMULLROM)))
        .addAnimation("head", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(-2F, 0F, 0F), CATMULLROM),
            new Keyframe(0.25F, KeyframeAnimations.degreeVec(0.13F, -2.13F, 0.67F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(4.79F, -6.79F, 2.61F), CATMULLROM),
            new Keyframe(0.75F, KeyframeAnimations.degreeVec(7.88F, -9.84F, 4.68F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.degreeVec(7.08F, -10.99F, 5.82F), CATMULLROM),
            new Keyframe(1.25F, KeyframeAnimations.degreeVec(5.99F, -13.39F, 6.02F), CATMULLROM),
            new Keyframe(1.5F, KeyframeAnimations.degreeVec(6.43F, -13.66F, 5.97F), CATMULLROM),
            new Keyframe(1.75F, KeyframeAnimations.degreeVec(7.36F, -10.74F, 4.1F), CATMULLROM),
            new Keyframe(2F, KeyframeAnimations.degreeVec(8.42F, -7.25F, 0F), CATMULLROM),
            new Keyframe(2.25F, KeyframeAnimations.degreeVec(9.27F, -6.08F, -0.01F), CATMULLROM),
            new Keyframe(2.5F, KeyframeAnimations.degreeVec(9.95F, -6.26F, 0F), CATMULLROM),
            new Keyframe(2.75F, KeyframeAnimations.degreeVec(9.73F, -6.63F, 0F), CATMULLROM),
            new Keyframe(3F, KeyframeAnimations.degreeVec(8.42F, -7.21F, 0F), CATMULLROM),
            new Keyframe(3.25F, KeyframeAnimations.degreeVec(7.01F, -7.72F, 0F), CATMULLROM),
            new Keyframe(3.5F, KeyframeAnimations.degreeVec(6.22F, -7.99F, 0F), CATMULLROM),
            new Keyframe(3.75F, KeyframeAnimations.degreeVec(5.01F, -7.08F, 0F), CATMULLROM),
            new Keyframe(4F, KeyframeAnimations.degreeVec(1.09F, -3.09F, 0F), CATMULLROM),
            new Keyframe(4.25F, KeyframeAnimations.degreeVec(-1.86F, -0.14F, 0F), CATMULLROM),
            new Keyframe(4.5F, KeyframeAnimations.degreeVec(-2.11F, 0.11F, 0F), CATMULLROM),
            new Keyframe(4.75F, KeyframeAnimations.degreeVec(-2.06F, 0.06F, 0F), CATMULLROM),
            new Keyframe(5F, KeyframeAnimations.degreeVec(-2F, 0F, 0F), CATMULLROM)))
        .addAnimation("right_arm", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(5.16F, -66F, 0.5F), CATMULLROM),
            new Keyframe(0.25F, KeyframeAnimations.degreeVec(-13.37F, -63.74F, 15.9F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(-19.78F, -49.99F, 46.34F), CATMULLROM),
            new Keyframe(0.75F, KeyframeAnimations.degreeVec(-50.54F, -34.77F, 59.94F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.degreeVec(-55.51F, -30.41F, 62.65F), CATMULLROM),
            new Keyframe(1.25F, KeyframeAnimations.degreeVec(-59.88F, -26.15F, 65.18F), CATMULLROM),
            new Keyframe(1.5F, KeyframeAnimations.degreeVec(-55.65F, -30.21F, 62.83F), CATMULLROM),
            new Keyframe(1.75F, KeyframeAnimations.degreeVec(-51.66F, -34.23F, 60.31F), CATMULLROM),
            new Keyframe(2F, KeyframeAnimations.degreeVec(-51.65F, -34.25F, 60.29F), CATMULLROM),
            new Keyframe(2.25F, KeyframeAnimations.degreeVec(-51.66F, -34.25F, 60.29F), CATMULLROM),
            new Keyframe(2.5F, KeyframeAnimations.degreeVec(-51.69F, -34.24F, 60.3F), CATMULLROM),
            new Keyframe(2.75F, KeyframeAnimations.degreeVec(-51.71F, -34.23F, 60.31F), CATMULLROM),
            new Keyframe(3F, KeyframeAnimations.degreeVec(-51.72F, -34.22F, 60.31F), CATMULLROM),
            new Keyframe(3.25F, KeyframeAnimations.degreeVec(-51.68F, -34.23F, 60.3F), CATMULLROM),
            new Keyframe(3.5F, KeyframeAnimations.degreeVec(-51.58F, -34.27F, 60.27F), CATMULLROM),
            new Keyframe(3.75F, KeyframeAnimations.degreeVec(-39.34F, -40.22F, 55.95F), CATMULLROM),
            new Keyframe(4F, KeyframeAnimations.degreeVec(-1.82F, -60.42F, 27.63F), CATMULLROM),
            new Keyframe(4.25F, KeyframeAnimations.degreeVec(4.04F, -65.92F, 1.34F), CATMULLROM),
            new Keyframe(4.5F, KeyframeAnimations.degreeVec(5.2F, -66F, 0.47F), CATMULLROM),
            new Keyframe(4.75F, KeyframeAnimations.degreeVec(5.19F, -66F, 0.48F), CATMULLROM),
            new Keyframe(5F, KeyframeAnimations.degreeVec(5.15F, -66F, 0.5F), CATMULLROM)))
        .addAnimation("left_arm", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(5.16F, 66F, -0.5F), CATMULLROM),
            new Keyframe(0.25F, KeyframeAnimations.degreeVec(5.16F, 66F, -0.5F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(5.16F, 66F, -0.5F), CATMULLROM),
            new Keyframe(0.75F, KeyframeAnimations.degreeVec(5.17F, 66F, -0.5F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.degreeVec(5.18F, 66F, -0.49F), CATMULLROM),
            new Keyframe(1.25F, KeyframeAnimations.degreeVec(5.18F, 66F, -0.49F), CATMULLROM),
            new Keyframe(1.5F, KeyframeAnimations.degreeVec(5.17F, 66F, -0.49F), CATMULLROM),
            new Keyframe(1.75F, KeyframeAnimations.degreeVec(5.16F, 66F, -0.5F), CATMULLROM),
            new Keyframe(2F, KeyframeAnimations.degreeVec(-7.83F, 62.12F, -22.37F), CATMULLROM),
            new Keyframe(2.25F, KeyframeAnimations.degreeVec(-89.61F, 49.88F, -46.44F), CATMULLROM),
            new Keyframe(2.5F, KeyframeAnimations.degreeVec(-88.63F, 48.89F, -47.66F), CATMULLROM),
            new Keyframe(2.75F, KeyframeAnimations.degreeVec(-88.64F, 48.9F, -47.65F), CATMULLROM),
            new Keyframe(3F, KeyframeAnimations.degreeVec(-88.64F, 48.9F, -47.65F), CATMULLROM),
            new Keyframe(3.25F, KeyframeAnimations.degreeVec(-88.68F, 48.89F, -47.66F), CATMULLROM),
            new Keyframe(3.5F, KeyframeAnimations.degreeVec(-25.29F, 59.43F, -30.2F), CATMULLROM),
            new Keyframe(3.75F, KeyframeAnimations.degreeVec(3.24F, 65.91F, -1.41F), CATMULLROM),
            new Keyframe(4F, KeyframeAnimations.degreeVec(5.07F, 65.99F, -0.54F), CATMULLROM),
            new Keyframe(4.25F, KeyframeAnimations.degreeVec(5.14F, 65.99F, -0.51F), CATMULLROM),
            new Keyframe(4.5F, KeyframeAnimations.degreeVec(5.16F, 66F, -0.5F), CATMULLROM),
            new Keyframe(4.75F, KeyframeAnimations.degreeVec(5.15F, 65.99F, -0.51F), CATMULLROM),
            new Keyframe(5F, KeyframeAnimations.degreeVec(5.16F, 66F, -0.5F), CATMULLROM)))
        .addAnimation("right_leg", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(-15.75F, 4.97F, 0.34F), CATMULLROM),
            new Keyframe(0.25F, KeyframeAnimations.degreeVec(-15.75F, 4.97F, 0.34F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(-15.75F, 4.97F, 0.34F), CATMULLROM),
            new Keyframe(0.75F, KeyframeAnimations.degreeVec(-15.75F, 4.97F, 0.34F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.degreeVec(-15.75F, 4.97F, 0.34F), CATMULLROM),
            new Keyframe(1.25F, KeyframeAnimations.degreeVec(-15.75F, 4.97F, 0.34F), CATMULLROM),
            new Keyframe(1.5F, KeyframeAnimations.degreeVec(-15.75F, 4.97F, 0.34F), CATMULLROM),
            new Keyframe(1.75F, KeyframeAnimations.degreeVec(-15.75F, 4.97F, 0.34F), CATMULLROM),
            new Keyframe(2F, KeyframeAnimations.degreeVec(-15.75F, 4.97F, 0.34F), CATMULLROM),
            new Keyframe(2.25F, KeyframeAnimations.degreeVec(-15.75F, 4.97F, 0.34F), CATMULLROM),
            new Keyframe(2.5F, KeyframeAnimations.degreeVec(-15.75F, 4.97F, 0.34F), CATMULLROM),
            new Keyframe(2.75F, KeyframeAnimations.degreeVec(-15.75F, 4.97F, 0.34F), CATMULLROM),
            new Keyframe(3F, KeyframeAnimations.degreeVec(-15.75F, 4.97F, 0.34F), CATMULLROM),
            new Keyframe(3.25F, KeyframeAnimations.degreeVec(-15.75F, 4.97F, 0.34F), CATMULLROM),
            new Keyframe(3.5F, KeyframeAnimations.degreeVec(-15.75F, 4.97F, 0.34F), CATMULLROM),
            new Keyframe(3.75F, KeyframeAnimations.degreeVec(-15.75F, 4.97F, 0.34F), CATMULLROM),
            new Keyframe(4F, KeyframeAnimations.degreeVec(-15.75F, 4.97F, 0.34F), CATMULLROM),
            new Keyframe(4.25F, KeyframeAnimations.degreeVec(-15.75F, 4.97F, 0.34F), CATMULLROM),
            new Keyframe(4.5F, KeyframeAnimations.degreeVec(-15.75F, 4.97F, 0.34F), CATMULLROM),
            new Keyframe(4.75F, KeyframeAnimations.degreeVec(-15.75F, 4.97F, 0.34F), CATMULLROM),
            new Keyframe(5F, KeyframeAnimations.degreeVec(-15.75F, 4.97F, 0.34F), CATMULLROM)))
        .addAnimation("left_leg", new AnimationChannel(ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(-18.5F, -10.97F, -0.84F), CATMULLROM),
            new Keyframe(0.25F, KeyframeAnimations.degreeVec(-18.5F, -10.97F, -0.84F), CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(-18.5F, -10.97F, -0.84F), CATMULLROM),
            new Keyframe(0.75F, KeyframeAnimations.degreeVec(-18.5F, -10.97F, -0.84F), CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.degreeVec(-18.5F, -10.97F, -0.84F), CATMULLROM),
            new Keyframe(1.25F, KeyframeAnimations.degreeVec(-18.5F, -10.97F, -0.84F), CATMULLROM),
            new Keyframe(1.5F, KeyframeAnimations.degreeVec(-18.5F, -10.97F, -0.84F), CATMULLROM),
            new Keyframe(1.75F, KeyframeAnimations.degreeVec(-18.5F, -10.97F, -0.84F), CATMULLROM),
            new Keyframe(2F, KeyframeAnimations.degreeVec(-18.5F, -10.97F, -0.84F), CATMULLROM),
            new Keyframe(2.25F, KeyframeAnimations.degreeVec(-18.5F, -10.97F, -0.84F), CATMULLROM),
            new Keyframe(2.5F, KeyframeAnimations.degreeVec(-18.5F, -10.97F, -0.84F), CATMULLROM),
            new Keyframe(2.75F, KeyframeAnimations.degreeVec(-18.5F, -10.97F, -0.84F), CATMULLROM),
            new Keyframe(3F, KeyframeAnimations.degreeVec(-18.5F, -10.97F, -0.84F), CATMULLROM),
            new Keyframe(3.25F, KeyframeAnimations.degreeVec(-18.5F, -10.97F, -0.84F), CATMULLROM),
            new Keyframe(3.5F, KeyframeAnimations.degreeVec(-18.5F, -10.97F, -0.84F), CATMULLROM),
            new Keyframe(3.75F, KeyframeAnimations.degreeVec(-18.5F, -10.97F, -0.84F), CATMULLROM),
            new Keyframe(4F, KeyframeAnimations.degreeVec(-18.5F, -10.97F, -0.84F), CATMULLROM),
            new Keyframe(4.25F, KeyframeAnimations.degreeVec(-18.5F, -10.97F, -0.84F), CATMULLROM),
            new Keyframe(4.5F, KeyframeAnimations.degreeVec(-18.5F, -10.97F, -0.84F), CATMULLROM),
            new Keyframe(4.75F, KeyframeAnimations.degreeVec(-18.5F, -10.97F, -0.84F), CATMULLROM),
            new Keyframe(5F, KeyframeAnimations.degreeVec(-18.51F, -10.97F, -0.84F), CATMULLROM)))
        .build();
}
