package com.hearthstead.client.ui;

import com.hearthstead.Hearthstead;
import net.minecraft.client.gui.Font;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.Renderable;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;

/**
 * The drawing half of the Hearthstead UI kit.
 *
 * <p>Screens are written in terms of panels, cards, rows and rules rather than
 * in terms of rectangles. Two reasons, and the second is the one that matters:
 *
 * <ol>
 *   <li>Every surface here is a <b>nine-slice sprite</b> from the GUI atlas, so
 *       one 18x18 image is a panel at any size. The old screens either blitted
 *       a whole 256x256 PNG — fixing the panel at one size forever — or stacked
 *       {@code fill} rectangles, which always looks like a stack of rectangles.
 *   <li>Every number comes from {@link HsUiTokens}, which is generated from the
 *       same {@code tools/ui/tokens.json} the offline preview renders from. A
 *       preview drawn from different numbers than the game is a preview that
 *       lies, and the whole point of the preview is that it can be trusted.
 *   </li>
 * </ol>
 *
 * <p>Sprite paths are relative to {@code textures/gui/sprites} with no
 * extension — that is what the atlas wants — and every sprite's scaling rule
 * lives beside it in a {@code .mcmeta}. Both are generated by
 * {@code tools/gen_ui.py}; edit the generator, never the PNG.
 */
public final class HsUi {

    /**
     * Draws a screen's widgets WITHOUT repainting the blurred background --
     * the thing {@code super.render()} cannot be used for once a screen has
     * already drawn its own panel.
     *
     * <h2>Why this exists</h2>
     *
     * <p>Vanilla's {@code Screen#render} opens with
     * {@code this.renderBackground(...)}, and in 1.21 that is not a cheap
     * fill: it runs {@code renderBlurredBackground} and then
     * {@code renderMenuBackground}. Every Hearthstead screen was written in
     * the shape
     *
     * <pre>
     *   renderBackground(...);   // blur + darken, pass 1
     *   ...draw the whole panel...
     *   super.render(...);       // blur + darken AGAIN, over the panel
     * </pre>
     *
     * <p>so the second pass blurred and darkened everything the screen had
     * just drawn, while the buttons -- rendered by that same
     * {@code super.render} call, after its background -- came out crisp. That
     * is exactly the symptom that was reported and twice misdiagnosed: a
     * blurred panel with sharp buttons on top of it, on every screen at once.
     * It was briefly blamed on the harness's software rasteriser, because
     * vanilla's own pause menu also looks soft under llvmpipe. That was a
     * true observation about a different thing; this double pass is real, it
     * is ours, and it is visible on any hardware.
     *
     * <p>Calling this instead of {@code super.render(...)} keeps the draw
     * order identical -- background, panel, widgets -- with exactly one
     * background pass. {@code Screen#renderables} is public in 1.21.1, so
     * this needs no access widener and no mixin.
     */
    public static void widgets(Screen screen, GuiGraphics g, int mouseX, int mouseY,
                               float partialTick) {
        for (Renderable renderable : screen.renderables) {
            renderable.render(g, mouseX, mouseY, partialTick);
        }
    }

    // -- sprites ----------------------------------------------------------

    public static final ResourceLocation WINDOW = sprite("panel/window");
    public static final ResourceLocation INSET = sprite("panel/inset");
    public static final ResourceLocation CARD = sprite("panel/card");
    public static final ResourceLocation CARD_HOVER = sprite("panel/card_hover");
    public static final ResourceLocation DIVIDER = sprite("widget/divider");
    public static final ResourceLocation SLOT = sprite("widget/slot");
    public static final ResourceLocation SCROLL_TRACK = sprite("widget/scroll_track");
    public static final ResourceLocation SCROLL_THUMB = sprite("widget/scroll_thumb");
    public static final ResourceLocation SCROLL_THUMB_HOVER =
        sprite("widget/scroll_thumb_hover");
    public static final ResourceLocation TAB_SELECTED = sprite("widget/tab_selected");
    public static final ResourceLocation TAB_UNSELECTED = sprite("widget/tab_unselected");
    public static final ResourceLocation BAR_TRACK = sprite("bar/track");
    public static final ResourceLocation PIP_EMPTY = sprite("widget/pip_empty");

    private static ResourceLocation sprite(String path) {
        return ResourceLocation.fromNamespaceAndPath(Hearthstead.MODID, path);
    }

    /** The tone a value carries: good, warning, bad — for pips, bars and text. */
    public enum Tone {
        ACCENT("accent", HsUiTokens.ACCENT),
        GOOD("good", HsUiTokens.GOOD),
        WARN("warn", HsUiTokens.WARN),
        BAD("bad", HsUiTokens.BAD);

        private final String key;
        private final int colour;

        Tone(String key, int colour) {
            this.key = key;
            this.colour = colour;
        }

        public int colour() {
            return colour;
        }

        public ResourceLocation pip() {
            return sprite("widget/pip_" + key);
        }

        public ResourceLocation barFill() {
            return sprite("bar/fill_" + (this == ACCENT ? "good" : key));
        }

        /** The tone a 0..1 ratio deserves, so bars and pips agree everywhere. */
        public static Tone of(float ratio) {
            return ratio >= 0.7F ? GOOD : ratio >= 0.35F ? WARN : BAD;
        }
    }

    // -- surfaces ---------------------------------------------------------

    public static void window(GuiGraphics g, int x, int y, int w, int h) {
        g.blitSprite(WINDOW, x, y, w, h);
    }

    public static void inset(GuiGraphics g, int x, int y, int w, int h) {
        g.blitSprite(INSET, x, y, w, h);
    }

    public static void card(GuiGraphics g, int x, int y, int w, int h,
                            boolean hovered) {
        g.blitSprite(hovered ? CARD_HOVER : CARD, x, y, w, h);
    }

    public static void slot(GuiGraphics g, int x, int y) {
        g.blitSprite(SLOT, x, y, HsUiTokens.SLOT, HsUiTokens.SLOT);
    }

    /** A ruled line. Thin geometry is measured in screen pixels, not intent —
     *  the plaque's rules were invisible in game at under two pixels. */
    public static void divider(GuiGraphics g, int x, int y, int w) {
        g.blitSprite(DIVIDER, x, y, w, HsUiTokens.DIVIDER_H);
    }

    public static void tab(GuiGraphics g, int x, int y, int w, int h,
                           boolean selected) {
        g.blitSprite(selected ? TAB_SELECTED : TAB_UNSELECTED, x, y, w, h);
    }

    // -- values -----------------------------------------------------------

    /**
     * A rating drawn as pips. Pips beat printed integers because you read
     * "four of five" at a glance and never read "4" at a glance — which is
     * exactly the complaint about MineColonies' column of numbers.
     */
    public static void pips(GuiGraphics g, int x, int y, int filled, int of,
                            Tone tone) {
        ResourceLocation full = tone.pip();
        for (int i = 0; i < of; i++) {
            g.blitSprite(i < filled ? full : PIP_EMPTY, x + i * 6, y, 5, 5);
        }
    }

    public static void bar(GuiGraphics g, int x, int y, int w, int h,
                           float ratio, Tone tone) {
        g.blitSprite(BAR_TRACK, x, y, w, h);
        int fill = Math.round((w - 2) * Math.max(0.0F, Math.min(1.0F, ratio)));
        if (fill > 0) {
            g.blitSprite(tone.barFill(), x + 1, y + 1, fill, h - 2);
        }
    }

    public static void scrollbar(GuiGraphics g, int x, int y, int h,
                                 float shown, float offset, boolean hovered) {
        g.blitSprite(SCROLL_TRACK, x, y, HsUiTokens.SCROLL_W, h);
        if (shown >= 1.0F) {
            return;
        }
        int thumb = Math.max(8, Math.round(h * shown));
        int top = y + Math.round((h - thumb) * offset);
        g.blitSprite(hovered ? SCROLL_THUMB_HOVER : SCROLL_THUMB,
            x, top, HsUiTokens.SCROLL_W, thumb);
    }

    // -- text -------------------------------------------------------------

    /**
     * A short trade badge: the identity colour as a dim fill with a bright
     * rim, the same colour again for the text — the "profession badge in
     * trade colour" the citizen-card recipe calls for, built without a new
     * sprite. The fill mixes toward {@code oak_carved[0]} (texlib's darkest
     * oak stop, not pure black) so it sits on the same ramp as the rest of
     * the dark ground rather than introducing a foreign grey.
     *
     * <p>Ellipsises inside {@code maxWidth} exactly like {@link #labelIn},
     * and returns the drawn width so a caller can lay out what comes next
     * (a mayor mark, say) beside it without guessing.
     */
    public static int badge(GuiGraphics g, Font font, Component text, int x, int y,
                            int maxWidth, int trade) {
        int innerMax = Math.max(0, maxWidth - 6);
        int inner = Math.min(font.width(text), innerMax);
        int w = inner + 6;
        int h = 10;
        int rim = 0xFF000000 | (trade & 0xFFFFFF);
        int fill = mixToward(trade, 0x241A0E, 0.62F);
        g.fill(x, y, x + w, y + h, fill);
        g.fill(x, y, x + w, y + 1, rim);
        g.fill(x, y + h - 1, x + w, y + h, rim);
        g.fill(x, y, x + 1, y + h, rim);
        g.fill(x + w - 1, y, x + w, y + h, rim);
        labelIn(g, font, text, x + 3, y + 1, inner, rim);
        return w;
    }

    /** Blends {@code rgb} toward {@code towardRgb} by {@code t} (0..1), alpha forced opaque. */
    private static int mixToward(int rgb, int towardRgb, float t) {
        int r = Math.round(((rgb >> 16) & 0xFF) * (1 - t) + ((towardRgb >> 16) & 0xFF) * t);
        int g2 = Math.round(((rgb >> 8) & 0xFF) * (1 - t) + ((towardRgb >> 8) & 0xFF) * t);
        int b = Math.round((rgb & 0xFF) * (1 - t) + (towardRgb & 0xFF) * t);
        return 0xFF000000 | (r << 16) | (g2 << 8) | b;
    }

    public static void label(GuiGraphics g, Font font, Component text,
                             int x, int y, int colour) {
        g.drawString(font, text, x, y, colour, true);
    }

    public static void centred(GuiGraphics g, Font font, Component text,
                               int centreX, int y, int colour) {
        g.drawString(font, text, centreX - font.width(text) / 2, y, colour, true);
    }

    public static void right(GuiGraphics g, Font font, Component text,
                             int rightX, int y, int colour) {
        g.drawString(font, text, rightX - font.width(text), y, colour, true);
    }

    /**
     * Draws inside a box, ellipsising rather than overrunning.
     *
     * <p>Use this for anything a player or a translator can make longer than
     * you expected — names, building titles, the reason a hire costs something.
     * The offline preview reports the same overflow before the game ever runs;
     * this is the safety net for the cases it cannot know about.
     */
    public static void labelIn(GuiGraphics g, Font font, Component text,
                               int x, int y, int box, int colour) {
        Component shown = font.width(text) <= box
            ? text
            : Component.literal(font.plainSubstrByWidth(text.getString(),
                box - font.width("...")) + "...");
        g.drawString(font, shown, x, y, colour, true);
    }

    // -- layout -----------------------------------------------------------

    /**
     * A downward cursor. Rows advance by their own height plus one gutter, so
     * a screen's vertical rhythm is stated once instead of being re-derived at
     * every call site — which is where inconsistent gutters come from, and
     * inconsistent gutters are the main reason a modded screen reads as
     * amateur beside a vanilla one.
     */
    public static final class Column {
        private final int x;
        private final int width;
        private final int gutter;
        private int y;

        public Column(int x, int y, int width) {
            this(x, y, width, HsUiTokens.GUTTER);
        }

        public Column(int x, int y, int width, int gutter) {
            this.x = x;
            this.y = y;
            this.width = width;
            this.gutter = gutter;
        }

        public int x() {
            return x;
        }

        public int width() {
            return width;
        }

        public int y() {
            return y;
        }

        /** Reserves a row and returns its top edge. */
        public int row(int height) {
            int top = y;
            y += height + gutter;
            return top;
        }

        public void skip(int pixels) {
            y += pixels;
        }

        /** Total height consumed, without the trailing gutter. */
        public int height(int from) {
            return y - from - gutter;
        }
    }

    private HsUi() {
    }
}
