package com.hearthstead.client.ui;

/**
 * GENERATED by tools/gen_ui.py -- do not edit by hand.
 *
 * <p>The design tokens the screens and the offline preview share. One
 * source, two consumers: a preview that renders from different numbers
 * than the game is a preview that lies.
 */
public final class HsUiTokens {

    public static final int ACCENT = 0xFFB8912F;
    public static final int BAD = 0xFF8A3A35;
    public static final int FIELD = 0xFF1A1A1A;
    public static final int GOOD = 0xFF5FA860;
    public static final int ROW_ODD = 0xFF212121;
    public static final int SHADOW = 0x66000000;
    public static final int TEXT = 0xFFE8E0D0;
    public static final int TEXT_MUTED = 0xFF8A8578;
    public static final int TEXT_ON_LIGHT = 0xFF241A0E;
    public static final int TEXT_STRONG = 0xFFF2ECDC;
    public static final int WARN = 0xFFC98A2E;

    public static final int BUTTON_H = 20;
    public static final int CARD_H = 36;
    public static final int DIVIDER_H = 2;
    public static final int GRID = 4;
    public static final int GUTTER = 4;
    public static final int LINE_GAP = 11;
    public static final int PAD = 8;
    public static final int ROW_H = 20;
    public static final int SCROLL_W = 6;
    public static final int SLOT = 18;
    public static final int TEXT_H = 8;
    public static final int TITLE_H = 16;

    private HsUiTokens() {
    }
}
