package com.hearthstead.client.ui;

import com.hearthstead.Hearthstead;
import net.minecraft.client.gui.Font;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;

/**
 * The drawing half of the Hearthstead UI kit.
 *
 * <p>Screens are written in terms of panels, cards, rows and rules rather than
 * in terms of rectangles. Two reasons, and the second is the one that matters:
 *
 * <ol>
 *   <li>Every surface here is a <b>nine-slice sprite</b> from the GUI atlas, so
 *       one 18x18 image is a panel at any size. The old screens either blitted
 *       a whole 256x256 PNG — fixing the panel at one size forever — or stacked
 *       {@code fill} rectangles, which always looks like a stack of rectangles.
 *   <li>Every number comes from {@link HsUiTokens}, which is generated from the
 *       same {@code tools/ui/tokens.json} the offline preview renders from. A
 *       preview drawn from different numbers than the game is a preview that
 *       lies, and the whole point of the preview is that it can be trusted.
 *   </li>
 * </ol>
 *
 * <p>Sprite paths are relative to {@code textures/gui/sprites} with no
 * extension — that is what the atlas wants — and every sprite's scaling rule
 * lives beside it in a {@code .mcmeta}. Both are generated by
 * {@code tools/gen_ui.py}; edit the generator, never the PNG.
 */
public final class HsUi {

    // -- sprites ----------------------------------------------------------

    public static final ResourceLocation WINDOW = sprite("panel/window");
    public static final ResourceLocation INSET = sprite("panel/inset");
    public static final ResourceLocation CARD = sprite("panel/card");
    public static final ResourceLocation CARD_HOVER = sprite("panel/card_hover");
    public static final ResourceLocation DIVIDER = sprite("widget/divider");
    public static final ResourceLocation SLOT = sprite("widget/slot");
    public static final ResourceLocation SCROLL_TRACK = sprite("widget/scroll_track");
    public static final ResourceLocation SCROLL_THUMB = sprite("widget/scroll_thumb");
    public static final ResourceLocation SCROLL_THUMB_HOVER =
        sprite("widget/scroll_thumb_hover");
    public static final ResourceLocation TAB_SELECTED = sprite("widget/tab_selected");
    public static final ResourceLocation TAB_UNSELECTED = sprite("widget/tab_unselected");
    public static final ResourceLocation BAR_TRACK = sprite("bar/track");
    public static final ResourceLocation PIP_EMPTY = sprite("widget/pip_empty");

    private static ResourceLocation sprite(String path) {
        return ResourceLocation.fromNamespaceAndPath(Hearthstead.MODID, path);
    }

    /** The tone a value carries: good, warning, bad — for pips, bars and text. */
    public enum Tone {
        ACCENT("accent", HsUiTokens.ACCENT),
        GOOD("good", HsUiTokens.GOOD),
        WARN("warn", HsUiTokens.WARN),
        BAD("bad", HsUiTokens.BAD);

        private final String key;
        private final int colour;

        Tone(String key, int colour) {
            this.key = key;
            this.colour = colour;
        }

        public int colour() {
            return colour;
        }

        public ResourceLocation pip() {
            return sprite("widget/pip_" + key);
        }

        public ResourceLocation barFill() {
            return sprite("bar/fill_" + (this == ACCENT ? "good" : key));
        }

        /** The tone a 0..1 ratio deserves, so bars and pips agree everywhere. */
        public static Tone of(float ratio) {
            return ratio >= 0.7F ? GOOD : ratio >= 0.35F ? WARN : BAD;
        }
    }

    // -- surfaces ---------------------------------------------------------

    public static void window(GuiGraphics g, int x, int y, int w, int h) {
        g.blitSprite(WINDOW, x, y, w, h);
    }

    public static void inset(GuiGraphics g, int x, int y, int w, int h) {
        g.blitSprite(INSET, x, y, w, h);
    }

    public static void card(GuiGraphics g, int x, int y, int w, int h,
                            boolean hovered) {
        g.blitSprite(hovered ? CARD_HOVER : CARD, x, y, w, h);
    }

    public static void slot(GuiGraphics g, int x, int y) {
        g.blitSprite(SLOT, x, y, HsUiTokens.SLOT, HsUiTokens.SLOT);
    }

    /** A ruled line. Thin geometry is measured in screen pixels, not intent —
     *  the plaque's rules were invisible in game at under two pixels. */
    public static void divider(GuiGraphics g, int x, int y, int w) {
        g.blitSprite(DIVIDER, x, y, w, HsUiTokens.DIVIDER_H);
    }

    public static void tab(GuiGraphics g, int x, int y, int w, int h,
                           boolean selected) {
        g.blitSprite(selected ? TAB_SELECTED : TAB_UNSELECTED, x, y, w, h);
    }

    // -- values -----------------------------------------------------------

    /**
     * A rating drawn as pips. Pips beat printed integers because you read
     * "four of five" at a glance and never read "4" at a glance — which is
     * exactly the complaint about MineColonies' column of numbers.
     */
    public static void pips(GuiGraphics g, int x, int y, int filled, int of,
                            Tone tone) {
        ResourceLocation full = tone.pip();
        for (int i = 0; i < of; i++) {
            g.blitSprite(i < filled ? full : PIP_EMPTY, x + i * 6, y, 5, 5);
        }
    }

    public static void bar(GuiGraphics g, int x, int y, int w, int h,
                           float ratio, Tone tone) {
        g.blitSprite(BAR_TRACK, x, y, w, h);
        int fill = Math.round((w - 2) * Math.max(0.0F, Math.min(1.0F, ratio)));
        if (fill > 0) {
            g.blitSprite(tone.barFill(), x + 1, y + 1, fill, h - 2);
        }
    }

    public static void scrollbar(GuiGraphics g, int x, int y, int h,
                                 float shown, float offset, boolean hovered) {
        g.blitSprite(SCROLL_TRACK, x, y, HsUiTokens.SCROLL_W, h);
        if (shown >= 1.0F) {
            return;
        }
        int thumb = Math.max(8, Math.round(h * shown));
        int top = y + Math.round((h - thumb) * offset);
        g.blitSprite(hovered ? SCROLL_THUMB_HOVER : SCROLL_THUMB,
            x, top, HsUiTokens.SCROLL_W, thumb);
    }

    // -- text -------------------------------------------------------------

    public static void label(GuiGraphics g, Font font, Component text,
                             int x, int y, int colour) {
        g.drawString(font, text, x, y, colour, true);
    }

    public static void centred(GuiGraphics g, Font font, Component text,
                               int centreX, int y, int colour) {
        g.drawString(font, text, centreX - font.width(text) / 2, y, colour, true);
    }

    public static void right(GuiGraphics g, Font font, Component text,
                             int rightX, int y, int colour) {
        g.drawString(font, text, rightX - font.width(text), y, colour, true);
    }

    /**
     * Draws inside a box, ellipsising rather than overrunning.
     *
     * <p>Use this for anything a player or a translator can make longer than
     * you expected — names, building titles, the reason a hire costs something.
     * The offline preview reports the same overflow before the game ever runs;
     * this is the safety net for the cases it cannot know about.
     */
    public static void labelIn(GuiGraphics g, Font font, Component text,
                               int x, int y, int box, int colour) {
        Component shown = font.width(text) <= box
            ? text
            : Component.literal(font.plainSubstrByWidth(text.getString(),
                box - font.width("...")) + "...");
        g.drawString(font, shown, x, y, colour, true);
    }

    // -- layout -----------------------------------------------------------

    /**
     * A downward cursor. Rows advance by their own height plus one gutter, so
     * a screen's vertical rhythm is stated once instead of being re-derived at
     * every call site — which is where inconsistent gutters come from, and
     * inconsistent gutters are the main reason a modded screen reads as
     * amateur beside a vanilla one.
     */
    public static final class Column {
        private final int x;
        private final int width;
        private final int gutter;
        private int y;

        public Column(int x, int y, int width) {
            this(x, y, width, HsUiTokens.GUTTER);
        }

        public Column(int x, int y, int width, int gutter) {
            this.x = x;
            this.y = y;
            this.width = width;
            this.gutter = gutter;
        }

        public int x() {
            return x;
        }

        public int width() {
            return width;
        }

        public int y() {
            return y;
        }

        /** Reserves a row and returns its top edge. */
        public int row(int height) {
            int top = y;
            y += height + gutter;
            return top;
        }

        public void skip(int pixels) {
            y += pixels;
        }

        /** Total height consumed, without the trailing gutter. */
        public int height(int from) {
            return y - from - gutter;
        }
    }

    private HsUi() {
    }
}
