"""Shared pixel-art helpers for Hearthstead's deterministic texture pipeline.

Every texture in the mod is generated by code in this folder so the art is
original by construction, exactly sized, and reproducible. Light convention:
top-left key light — top faces brightest, front neutral, sides dimmed, back
and bottom darkest.
"""
import random
from PIL import Image

# ---------------------------------------------------------------- palette ---
# Grounded European medieval palette. Each ramp is dark -> light.
PALETTES = {
    "linen":     ["#8f8268", "#b3a582", "#cbbc97", "#e0d3b0", "#efe5c8"],
    "linen_raw": ["#7d7156", "#a08f6e", "#bfae8a", "#d6c7a2", "#e8dcc0"],
    "oak":       ["#3a2c19", "#4a3820", "#5a4429", "#6e5638", "#83694a"],
    "oak_light": ["#4a3820", "#5f4a2c", "#75603c", "#8a744e", "#9e8862"],
    "stone":     ["#4f4c40", "#62604f", "#75715f", "#8a8578", "#9c978a"],
    "leather":   ["#4a3116", "#64411f", "#7a5230", "#8d6238", "#a1774b"],
    "burgundy":  ["#4e2427", "#692f33", "#7e3b40", "#93494e", "#a65a5f"],
    "forest":    ["#2c3f27", "#3a5233", "#4a6741", "#5b7a50", "#6d8e61"],
    "wheat":     ["#8a6423", "#a87f2e", "#c29038", "#d9a94c", "#e8c06b"],
    "iron":      ["#26262b", "#35353a", "#46464c", "#57575e", "#6b6b73"],
    "amber":     ["#b06a1e", "#d18a2c", "#e8a33c", "#f5c56a", "#ffdd8e"],
    "ember":     ["#6b1d10", "#a33517", "#d95b1e", "#f08c2e", "#ffc45e"],
    "skin":      ["#8a5c3d", "#b07c55", "#c08d67", "#d9a886", "#e8bf9c"],
    "skin_tan":  ["#6e4426", "#8a5c3d", "#a06f47", "#b58256", "#c99668"],
    "hair_brn":  ["#241609", "#3a2712", "#4e351b", "#5f4424", "#6f522e"],
    "hair_blnd": ["#4e3a1a", "#6e5527", "#8a6e35", "#a08344", "#b39755"],
    "hair_blk":  ["#0d0c0c", "#191717", "#242121", "#2f2b2a", "#3a3533"],
    "hair_red":  ["#3f1d0d", "#5a2c12", "#743c19", "#8a4b20", "#9c5a29"],
    "wool_gray": ["#4a4842", "#5c5a52", "#6e6b61", "#807d71", "#918e80"],
    "gambeson":  ["#5a5648", "#6d6857", "#7f7a66", "#918b75", "#a29c84"],
    "straw":     ["#7d6222", "#9c7d2c", "#b89536", "#cfab45", "#e0be5c"],
    "parchment": ["#a8946a", "#c2ad7f", "#d6c294", "#e5d3a8", "#efe0bd"],
    "ink":       ["#241c12", "#3f3024", "#54432f", "#69573c", "#7d6a4a"],
}


def hx(s):
    """'#rrggbb' -> (r, g, b, 255)."""
    s = s.lstrip("#")
    return (int(s[0:2], 16), int(s[2:4], 16), int(s[4:6], 16), 255)


def ramp(name):
    return [hx(c) for c in PALETTES[name]]


def shade(color, f):
    r, g, b, a = color
    return (max(0, min(255, int(r * f))), max(0, min(255, int(g * f))),
            max(0, min(255, int(b * f))), a)


def mix(c1, c2, t):
    return tuple(int(a + (b - a) * t) for a, b in zip(c1, c2))


def new_image(w, h):
    return Image.new("RGBA", (w, h), (0, 0, 0, 0))


def fill(img, x, y, w, h, color):
    px = img.load()
    for j in range(y, y + h):
        for i in range(x, x + w):
            if 0 <= i < img.width and 0 <= j < img.height:
                px[i, j] = color


def put(img, x, y, color):
    if 0 <= x < img.width and 0 <= y < img.height:
        img.load()[x, y] = color


def cloth(img, x, y, w, h, ramp_colors, rng, base_idx=3, weave=0.35,
          v_grad=0.12, h_grad=0.0):
    """Fabric fill: base tone + woven noise + a soft vertical gradient."""
    px = img.load()
    n = len(ramp_colors)
    for j in range(h):
        gv = 1.0 - v_grad * (j / max(1, h - 1))
        for i in range(w):
            gh = 1.0 - h_grad * abs((i / max(1, w - 1)) - 0.5) * 2
            idx = base_idx
            r = rng.random()
            if r < weave * 0.45:
                idx = max(0, base_idx - 1)
            elif r < weave * 0.55:
                idx = min(n - 1, base_idx + 1)
            elif r < weave * 0.60:
                idx = max(0, base_idx - 2)
            c = shade(ramp_colors[idx], gv * gh)
            px[x + i, y + j] = c


def stone(img, x, y, w, h, ramp_colors, rng, block_w=(3, 5), block_h=(2, 3)):
    """Fieldstone fill: irregular courses of stones with dark mortar seams."""
    mortar = shade(ramp_colors[0], 0.85)
    fill(img, x, y, w, h, mortar)
    j = 0
    row = 0
    while j < h:
        bh = rng.randint(*block_h)
        i = -rng.randint(0, 2) if row % 2 else 0
        while i < w:
            bw = rng.randint(*block_w)
            base = rng.choice(ramp_colors[1:4])
            for jj in range(max(0, j), min(h, j + bh - 1)):
                for ii in range(max(0, i), min(w, i + bw - 1)):
                    f = 1.0
                    if jj == j:
                        f = 1.12          # top catch-light
                    elif jj == j + bh - 2:
                        f = 0.9
                    if ii == max(0, i):
                        f *= 1.04
                    c = shade(base, f * (0.94 + rng.random() * 0.12))
                    px = img.load()
                    px[x + ii, y + jj] = c
            i += bw
        j += bh
        row += 1


def planks(img, x, y, w, h, ramp_colors, rng, vertical=False, board=4):
    """Weathered plank fill with grain streaks and seams."""
    px = img.load()
    for j in range(h):
        for i in range(w):
            along, across = (j, i) if vertical else (i, j)
            seam = (across % board) == board - 1
            idx = 3
            r = rng.random()
            if r < 0.30:
                idx = 2
            elif r < 0.38:
                idx = 4
            if (along * 7 + across * 13) % 11 == 0:
                idx = 1                    # grain streak
            c = ramp_colors[0] if seam else ramp_colors[idx]
            if not seam and (across % board) == 0:
                c = shade(c, 1.08)         # board edge highlight
            px[x + i, y + j] = c


def outline_rect(img, x, y, w, h, color):
    for i in range(x, x + w):
        put(img, i, y, color)
        put(img, i, y + h - 1, color)
    for j in range(y, y + h):
        put(img, x, j, color)
        put(img, x + w - 1, j, color)


def bevel(img, x, y, w, h, light, dark):
    """1px raised bevel: light on top/left, dark on bottom/right."""
    for i in range(x, x + w):
        put(img, i, y, light)
        put(img, i, y + h - 1, dark)
    for j in range(y, y + h):
        put(img, x, j, light)
        put(img, x + w - 1, j, dark)
    put(img, x + w - 1, y, mix(light, dark, 0.5))
    put(img, x, y + h - 1, mix(light, dark, 0.5))


def inset(img, x, y, w, h, light, dark):
    """1px sunken bevel: dark on top/left, light on bottom/right."""
    bevel(img, x, y, w, h, dark, light)


# ------------------------------------------------------------- box UV map ---
FACE_LIGHT = {"top": 1.14, "bottom": 0.62, "front": 1.0,
              "back": 0.82, "right": 0.90, "left": 0.90}


def box_faces(u, v, w, h, d):
    """Vanilla box UV layout -> face name to (x, y, width, height) rects.

    Layout:  [top][bottom] on the first d rows,
             [right][front][left][back] below.
    """
    return {
        "top":    (u + d,         v,     w, d),
        "bottom": (u + d + w,     v,     w, d),
        "right":  (u,             v + d, d, h),
        "front":  (u + d,         v + d, w, h),
        "left":   (u + d + w,     v + d, d, h),
        "back":   (u + d + w + d, v + d, w, h),
    }


def paint_box(img, u, v, w, h, d, painter):
    """Call painter(face_name, x, y, fw, fh, light_factor) for all six faces."""
    for face, (x, y, fw, fh) in box_faces(u, v, w, h, d).items():
        painter(face, x, y, fw, fh, FACE_LIGHT[face])


def scale_check(img, expect_w, expect_h, name):
    assert img.size == (expect_w, expect_h), \
        f"{name}: {img.size} != {(expect_w, expect_h)}"


def save(img, path):
    import os
    os.makedirs(os.path.dirname(path), exist_ok=True)
    img.save(path)
    print(f"  wrote {path} ({img.width}x{img.height})")
