plugins {
    id 'java'
    id 'net.minecraftforge.gradle' version '[6.0.24,6.2)'
}

group = 'com.hearthstead'
version = mod_version

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: minecraft_version
    copyIdeResources = true

    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'info'
            mods {
                hearthstead {
                    source sourceSets.main
                }
            }
        }
        client {}
        server {
            args '--nogui'
        }
        gameTestServer {
            workingDirectory project.file('run/gametest')
            property 'forge.enabledGameTestNamespaces', 'hearthstead'
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

jar {
    manifest {
        attributes(
            'Specification-Title'     : 'hearthstead',
            'Specification-Vendor'    : 'Hearthstead',
            'Specification-Version'   : '1',
            'Implementation-Title'    : 'Hearthstead',
            'Implementation-Version'  : mod_version,
            'Implementation-Vendor'   : 'Hearthstead'
        )
    }
    finalizedBy 'reobfJar'
}
